### ISSUE TITLE
Problem running turbine.py

### ISSUE THREAD

**Issue by taylor-parsons** [WISDEM/WISDEM#20]
I created a virtual machine on my Windows computer running Ubuntu as the guest. All OpenMDAO tests were passed, dependencies are installed, and the setup_all returns everything was installed correctly. When running turbine.py my error seems to be with connections in OpenMDAO:

(openmdao-0.12.0)tparsons@tparsons-VirtualBox:~/Documents/SE_Docs/WISDEM/src/wisdem/turbinese$ python turbine.py
/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/setuptools-0.9.5-py2.7.egg/pkg_resources.py:1054: UserWarning: /home/tparsons/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Traceback (most recent call last):
  File "turbine.py", line 345, in <module>
    turbine = TurbineSE()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 182, in __init__
    set_as_top(self, first_only=True)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 78, in set_as_top
    cont.cpath_updated()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 420, in cpath_updated
    self.configure()
  File "turbine.py", line 333, in configure
    configure_turbine(self)
  File "turbine.py", line 188, in configure_turbine
    assembly.add('rotor', RotorSE())
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 558, in add
    super(Component, self).add(name, obj)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 603, in add
    removed = self._prep_for_add(name, obj)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 592, in _prep_for_add
    obj.cpath_updated()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 420, in cpath_updated
    self.configure()
  File "/home/tparsons/Documents/SE_Docs/WISDEM/plugins/RotorSE/src/rotorse/rotor.py", line 2032, in configure
    self.connect('precurve_sub + delta_precurve_sub', 'spline.precurve_sub')
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 623, in connect
    sys.exc_info())
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 620, in connect
    self._connect(src, dst)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 642, in _connect
    pseudocomp.make_connections(self)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/pseudocomp.py", line 289, in make_connections
    scope.connect(src, dest)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 623, in connect
    sys.exc_info())
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 620, in connect
    self._connect(src, dst)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 670, in _connect
    destexpr.set(srcexpr.evaluate(), self)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/expreval.py", line 705, in set
    self._get_updated_scope(scope).set(self.text, val)  
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 1024, in set
    self.raise_exception(str(err), err.__class__)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 1353, in raise_exception
    raise exception_class(full_msg)
ValueError: rotor: Can't connect 'precurve_sub+delta_precurve_sub' to 'spline.precurve_sub': rotor: Can't connect '_pseudo_0.out0' to 'spline.precurve_sub': rotor: rotor.spline: Variable 'precurve_sub' must be an array-like object, but a value of None (<type 'NoneType'>) was specified.

**Comment by dykesk** [comment]
this is an issue with array specification and openmdao v 0.12; we will deal with this when we transition code for v 0.12

**Comment by dykesk** [comment]
closing - this is a general issue that will affect all WISDEM code when we update for new version of openmdao; for now, WISDEM users should use openmdao v 0.10.3.2 or earlier
