### ISSUE TITLE
Array broadcasting in drive.py, Linux

### ISSUE THREAD

**Issue by taylor-parsons** [WISDEM/WISDEM#21]
Still in a Linux guest machine, running drive.py returns the following error with the nacelle_System_I variable:

(openmdao-0.12.0)tparsons@tparsons-VirtualBox:~/Documents/SE_Docs/WISDEM/plugins/DriveSE/src/drivese$ python drive.py
----- NREL 5 MW Turbine - 3 Point Suspension -----
Traceback (most recent call last):
  File "drive.py", line 1194, in <module>
    nacelle_example_5MW_baseline_3pt()
  File "drive.py", line 740, in nacelle_example_5MW_baseline_3pt
    nace.run()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 520, in run
    self.execute()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 752, in execute
    self._system.run(self.itername, case_uuid=self._case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 1624, in run
    sub.run(iterbase, case_label=case_label, case_uuid=case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 1021, in run
    self._comp.run(case_uuid=case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/driver.py", line 431, in run
    super(Driver, self).run(case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 520, in run
    self.execute()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/driver.py", line 459, in execute
    self.run_iteration()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/driver.py", line 497, in run_iteration
    wf.run()
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/workflow.py", line 188, in run
    self._system.run(iterbase=iterbase, case_uuid=case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 1624, in run
    sub.run(iterbase, case_label=case_label, case_uuid=case_uuid)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 1026, in run
    self.vec['u'].set_from_scope(self.scope, vnames)
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/vecwrapper.py", line 291, in set_from_scope
    self[name] = scope.get_flattened_value(name[0]).real
  File "/home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/vecwrapper.py", line 84, in __setitem__
    (name, str(value), str(err)))
RuntimeError: cannot set array ('nacelleSystem.nacelle_I', ('nacelle_I',)) to value:
 [ 66146212.61456556   1706237.11484588   1611052.90064292         0.
         0.                 0.        ]
 could not broadcast input array from shape (6) into shape (3)

Running the same script on the host machine (Windows) returns no errors as input array seems to be shape(3) instead of shape(6).

**Comment by dykesk** [comment]
closing since this is for drivese; see issue there: https://github.com/WISDEM/DriveSE/issues/8
