### ISSUE TITLE
Error in rotor_cost.py when trying to use carbon in the spar caps.

### ISSUE THREAD

**Issue by diegoscmo** [WISDEM/WISDEM#273]
## Description
Error in rotor_cost.py when trying to use carbon in the spar caps.

### Steps to reproduce issue

1. Grab the carbon properties from examples\09_floating\nrel5mw-spar_oc3.yaml
2. Add this to the material properties in examples\03_blade\blade.yaml
3. Change the Spar_cap_ss and Spar_cap_ps material to carbon

Carbon properties from the model cited above are:
```
   -  E: [114500000000.0, 8390000000.0, 5990000000.0]
      name: CarbonUD
      G: [5990000000.0, 5990000000.0, 5990000000.0]
      rho: 1220.0
      orth: 1
      nu: [0.27, 0.27, 0.27]
      Xt: [2236.0e+006, 0.00, 0.00]
      Xc: [1528.0e+006, 0.00, 0.00]
      unit_cost: 30.00
      waste: 0.05
      fiber_density: 1800.
      area_density_dry: 1.000
      component_id: 4
```
I did try using other properties but ended up with the same issue.

### Current behavior
 I noticed that the variable **width_sc_hp** is read as:
` [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`

Since spar thickness is not read, there is an error:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2171, in _call_user_function
    yield
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 271, in _solve_nonlinear
    self._discrete_outputs)
  File "D:\repos\WISDEM\wisdem\rotorse\rotor_elasticity.py", line 972, in compute
    blade_cost, blade_mass = bcm.execute_blade_cost_model()
  File "D:\repos\WISDEM\wisdem\rotorse\rotor_cost.py", line 4361, in execute_blade_cost_model
    self.bom.extract_specs()
  File "D:\repos\WISDEM\wisdem\rotorse\rotor_cost.py", line 718, in extract_specs
    self.blade_specs["length_sc_hp"] = self.r[sc_end_section_hp] - self.r[sc_start_section_hp]  # [m]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "D:\repos\WISDEM\wisdem\main.py", line 79, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "D:\repos\WISDEM\wisdem\glue_code\runWISDEM.py", line 135, in run_wisdem
    wt_opt.run_driver()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 665, in run_driver
    return self.driver.run()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 262, in run
    model.run_solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 3772, in run_solve_nonlinear
    self._solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 764, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 559, in solve
    raise err
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 555, in solve
    self._solve()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 599, in _solve
    norm0, norm = self._iter_initialize()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_block_gs.py", line 109, in _iter_initialize
    return super()._iter_initialize()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 578, in _iter_initialize
    self._run_apply()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_block_gs.py", line 241, in _run_apply
    subsys._solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 764, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 764, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 273, in _solve_nonlinear
    self.compute(self._inputs, self._outputs)
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2177, in _call_user_function
    raise err_type(f"{self.msginfo}: Error calling {fname}(), {err}")
IndexError: 'wt.rotorse.re.precomp' <class RunPreComp>: Error calling compute(), only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

### Expected behavior

Doing the same without changing the material to carbon works normally.
**width_sc_hp** with glass material reads as:
```
 [0.         0.85674037 0.91391495 0.89549288 0.88760548 0.91179777
 0.87024119 0.8877145  0.89501048 0.8851515  0.92328614 0.9470053
 0.90767325 0.86967579 0.89384019 0.89264728 0.89967271 0.90050487
 0.93221451 0.91399162 0.9199017  0.91154324 0.9283896  0.88756723
 0.90979124 0.80783076 0.69342908 0.55009392 0.         0.        ]
```

### Code versions
- Using the latest develop branch

**Comment by gbarter** [comment]
Thank you for bringing this bug to our attention.  The indexing problem is now fixed in the `develop` branch.  Your modified yaml should now work fine.
