### ISSUE TITLE
Code not running after last git pull on branch develop

### ISSUE THREAD

**Issue by pollinico** [WISDEM/WISDEM#289]
## Description
A working code does not work anymore after last git pull on branch develop.  
V_mean input has been moved from modelling option to geometry option in environment.

### Steps to reproduce issue

  warnings.warn(warn)
Traceback (most recent call last):
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/system.py", line 2171, in _call_user_function
    yield
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/explicitcomponent.py", line 271, in _solve_nonlinear
    self._discrete_outputs)
  File "/home/nipol/Documents/Repos/WISDEM/wisdem/ccblade/ccblade_component.py", line 681, in compute
    myout, derivs = get_cp_cm.evaluate([inputs["Uhub"]], [Omega], [inputs["pitch"]], coefficients=True)
  File "/home/nipol/Documents/Repos/WISDEM/wisdem/ccblade/ccblade.py", line 1277, in evaluate
    Tsub, Ysub, Zsub, Qsub, Msub = _bem.thrusttorque(Np, Tp, *args)
ValueError: not enough values to unpack (expected 5, got 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nipol/Documents/Projects/Aegir/RunAEP/main_driver.py", line 213, in <module>
    wt_opt, analysis_options, opt_options = run_wisdem(fileWt, fileMod, fileAn)
  File "/home/nipol/Documents/Repos/WISDEM/wisdem/glue_code/runWISDEM.py", line 137, in run_wisdem
    wt_opt.run_model()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/problem.py", line 625, in run_model
    self.model.run_solve_nonlinear()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/system.py", line 3772, in run_solve_nonlinear
    self._solve_nonlinear()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 764, in _gs_iter
    subsys._solve_nonlinear()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 559, in solve
    raise err
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 555, in solve
    self._solve()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 599, in _solve
    norm0, norm = self._iter_initialize()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/nonlinear/nonlinear_block_gs.py", line 109, in _iter_initialize
    return super()._iter_initialize()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 578, in _iter_initialize
    self._run_apply()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/nonlinear/nonlinear_block_gs.py", line 241, in _run_apply
    subsys._solve_nonlinear()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/group.py", line 2636, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/solvers/solver.py", line 764, in _gs_iter
    subsys._solve_nonlinear()
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/explicitcomponent.py", line 273, in _solve_nonlinear
    self.compute(self._inputs, self._outputs)
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nipol/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/system.py", line 2177, in _call_user_function
    raise err_type(f"{self.msginfo}: Error calling {fname}(), {err}")
ValueError: 'wt.rotorse.ccblade' <class CCBladeTwist>: Error calling compute(), not enough values to unpack (expected 5, got 3)

**Comment by gbarter** [comment]
Hi Nicolo,

We greatly extended the gradients in CCBlade in the develop branch.  If you reinstall WISDEM, it should rebuild CCBlade.

**Comment by pollinico** [comment]
Thanks Garrett, I will try it.
