### ISSUE TITLE
Precomp improperly installed

### ISSUE THREAD

**Issue by evan-gaertner** [WISDEM/WISDEM#35]
I've tried installing all of the components to Wisdem and it reports that everything is installed correctly.  However when I test it with "import wisdem.lcoe.lcoe_se_assembly", it fails to find the precomp libraries.

Looking at the debug info for RotorSE, it appears to be deleting the entire "build\bdist.win32\egg" directory, where it expects the library to be.  The "build\bdist.win32" directory is indeed empty.  Do you have any suggestions? 

Thank you for your help!
Evan

```
>>> import wisdem.lcoe.lcoe_se_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\openmdao-0.9.7\wisdem\src\wisdem\lcoe\lcoe_se_assembly.py",
line 19, in <module>
    from wisdem.turbinese.turbine import configure_turbine
  File "c:\python27\openmdao-0.9.7\wisdem\src\wisdem\turbinese\turbine.py", line
 15, in <module>
    from rotorse.rotor import RotorSE
  File "C:\Python27\openmdao-0.9.7\lib\site-packages\rotorse-0.1.0-py2.7.egg\rot
orse\rotor.py", line 22, in <module>
    from precomp import Profile, Orthotropic2DMaterial, CompositeSection, _preco
mp
  File "C:\Python27\openmdao-0.9.7\lib\site-packages\rotorse-0.1.0-py2.7.egg\rot
orse\precomp.py", line 18, in <module>
    from _precomp import precomp as _precomp
  File "build\bdist.win32\egg\_precomp.py", line 7, in <module>
  File "build\bdist.win32\egg\_precomp.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified procedure could not be found.
```

```
(openmdao-0.9.7) C:\Python27\openmdao-0.9.7\WISDEM\plugins\RotorSE>python setup.
py install
running install
running bdist_egg
running egg_info
writing requirements to src\RotorSE.egg-info\requires.txt
writing src\RotorSE.egg-info\PKG-INFO
writing top-level names to src\RotorSE.egg-info\top_level.txt
writing dependency_links to src\RotorSE.egg-info\dependency_links.txt
reading manifest file 'src\RotorSE.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src\RotorSE.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\rotorse
creating build\bdist.win32\egg\rotorse\5MW_AFFiles
copying build\lib\rotorse\5MW_AFFiles\__init__.py -> build\bdist.win32\egg\rotor
se\5MW_AFFiles
creating build\bdist.win32\egg\rotorse\5MW_PreCompFiles
copying build\lib\rotorse\5MW_PreCompFiles\__init__.py -> build\bdist.win32\egg\
rotorse\5MW_PreCompFiles
copying build\lib\rotorse\precomp.py -> build\bdist.win32\egg\rotorse
copying build\lib\rotorse\rotor.py -> build\bdist.win32\egg\rotorse
copying build\lib\rotorse\rotoraero.py -> build\bdist.win32\egg\rotorse
copying build\lib\rotorse\rotoraerodefaults.py -> build\bdist.win32\egg\rotorse
creating build\bdist.win32\egg\rotorse\test
copying build\lib\rotorse\test\test_rotoraero_gradients.py -> build\bdist.win32\
egg\rotorse\test
copying build\lib\rotorse\test\test_rotor_gradients.py -> build\bdist.win32\egg\
rotorse\test
copying build\lib\rotorse\test\__init__.py -> build\bdist.win32\egg\rotorse\test

copying build\lib\rotorse\__init__.py -> build\bdist.win32\egg\rotorse
byte-compiling build\bdist.win32\egg\rotorse\5MW_AFFiles\__init__.py to __init__
.pyc
byte-compiling build\bdist.win32\egg\rotorse\5MW_PreCompFiles\__init__.py to __i
nit__.pyc
byte-compiling build\bdist.win32\egg\rotorse\precomp.py to precomp.pyc
byte-compiling build\bdist.win32\egg\rotorse\rotor.py to rotor.pyc
byte-compiling build\bdist.win32\egg\rotorse\rotoraero.py to rotoraero.pyc
byte-compiling build\bdist.win32\egg\rotorse\rotoraerodefaults.py to rotoraerode
faults.pyc
byte-compiling build\bdist.win32\egg\rotorse\test\test_rotoraero_gradients.py to
 test_rotoraero_gradients.pyc
byte-compiling build\bdist.win32\egg\rotorse\test\test_rotor_gradients.py to tes
t_rotor_gradients.pyc
byte-compiling build\bdist.win32\egg\rotorse\test\__init__.py to __init__.pyc
byte-compiling build\bdist.win32\egg\rotorse\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying src\RotorSE.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying src\RotorSE.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying src\RotorSE.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-I
NFO
copying src\RotorSE.egg-info\not-zip-safe -> build\bdist.win32\egg\EGG-INFO
copying src\RotorSE.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying src\RotorSE.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
creating 'dist\RotorSE-0.1.0-py2.7.egg' and adding 'build\bdist.win32\egg' to it

removing 'build\bdist.win32\egg' (and everything under it)
Processing RotorSE-0.1.0-py2.7.egg
removing 'c:\python27\openmdao-0.9.7\lib\site-packages\RotorSE-0.1.0-py2.7.egg'
(and everything under it)
creating c:\python27\openmdao-0.9.7\lib\site-packages\RotorSE-0.1.0-py2.7.egg
Extracting RotorSE-0.1.0-py2.7.egg to c:\python27\openmdao-0.9.7\lib\site-packag
es
Adding RotorSE 0.1.0 to easy-install.pth file

Installed c:\python27\openmdao-0.9.7\lib\site-packages\rotorse-0.1.0-py2.7.egg
Processing dependencies for RotorSE==0.1.0
Searching for pBEAM==0.1.0
Best match: pBEAM 0.1.0
Processing pbeam-0.1.0-py2.7-win32.egg
pbeam 0.1.0 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.9.7\lib\site-packages\pbeam-0.1.0-py2.7-win32.egg
Searching for CCBlade==1.1.1
Best match: CCBlade 1.1.1
CCBlade 1.1.1 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.9.7\wisdem\plugins\ccblade\src
Searching for CommonSE==0.1.3
Best match: CommonSE 0.1.3
CommonSE 0.1.3 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.9.7\wisdem\plugins\commonse\src
Searching for AirfoilPrep.py==0.1.0
Best match: AirfoilPrep.py 0.1.0
AirfoilPrep.py 0.1.0 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.9.7\wisdem\plugins\airfoilpreppy\src
Searching for akima==1.0.0
Best match: akima 1.0.0
Adding akima 1.0.0 to easy-install.pth file

Using c:\python27\openmdao-0.9.7\wisdem\plugins\akima\src
Finished processing dependencies for RotorSE==0.1.0
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "_precomp" sources
f2py options: []
  adding 'build\src.win32-2.7\fortranobject.c' to sources.
  adding 'build\src.win32-2.7' to include_dirs.
  adding 'build\src.win32-2.7\_precomp-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
writing src/rotorse\precomp.egg-info\PKG-INFO
writing top-level names to src/rotorse\precomp.egg-info\top_level.txt
writing dependency_links to src/rotorse\precomp.egg-info\dependency_links.txt
reading manifest file 'src/rotorse\precomp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src/rotorse\precomp.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
Cannot build msvcr library: "msvcr90d.dll" not found
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Found executable C:\MinGW\bin\gfortran.exe
Found executable C:\MinGW\bin\gfortran.exe
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
creating build\bdist.win32\egg
copying build\lib.win32-2.7\_curvefem.pyd -> build\bdist.win32\egg
copying build\lib.win32-2.7\_precomp.pyd -> build\bdist.win32\egg
creating stub loader for _precomp.pyd
byte-compiling build\bdist.win32\egg\_precomp.py to _precomp.pyc
creating build\bdist.win32\egg\EGG-INFO
copying src\rotorse\precomp.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-IN
FO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist\precomp-0.0.0-py2.7-win32.egg' and adding 'build\bdist.win32\egg'
 to it
**removing 'build\bdist.win32\egg' (and everything under it)**
Processing precomp-0.0.0-py2.7-win32.egg
Removing c:\python27\openmdao-0.9.7\lib\site-packages\precomp-0.0.0-py2.7-win32.
egg
Copying precomp-0.0.0-py2.7-win32.egg to c:\python27\openmdao-0.9.7\lib\site-pac
kages
Adding precomp 0.0.0 to easy-install.pth file

Installed c:\python27\openmdao-0.9.7\lib\site-packages\precomp-0.0.0-py2.7-win32
.egg
Processing dependencies for precomp==0.0.0
Finished processing dependencies for precomp==0.0.0
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "_curvefem" sources
f2py options: []
  adding 'build\src.win32-2.7\fortranobject.c' to sources.
  adding 'build\src.win32-2.7' to include_dirs.
build_src: building npy-pkg config files
writing src/rotorse\curvefem.egg-info\PKG-INFO
writing top-level names to src/rotorse\curvefem.egg-info\top_level.txt
writing dependency_links to src/rotorse\curvefem.egg-info\dependency_links.txt
reading manifest file 'src/rotorse\curvefem.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src/rotorse\curvefem.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
Cannot build msvcr library: "msvcr90d.dll" not found
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize GnuFCompiler
customize IntelVisualFCompiler
customize AbsoftFCompiler
customize CompaqVisualFCompiler
customize IntelItaniumVisualFCompiler
customize Gnu95FCompiler
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
creating build\bdist.win32\egg
copying build\lib.win32-2.7\_curvefem.pyd -> build\bdist.win32\egg
copying build\lib.win32-2.7\_precomp.pyd -> build\bdist.win32\egg
creating stub loader for _curvefem.pyd
byte-compiling build\bdist.win32\egg\_curvefem.py to _curvefem.pyc
creating build\bdist.win32\egg\EGG-INFO
copying src\rotorse\curvefem.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-I
NFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist\curvefem-0.0.0-py2.7-win32.egg' and adding 'build\bdist.win32\egg
' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing curvefem-0.0.0-py2.7-win32.egg
Removing c:\python27\openmdao-0.9.7\lib\site-packages\curvefem-0.0.0-py2.7-win32
.egg
Copying curvefem-0.0.0-py2.7-win32.egg to c:\python27\openmdao-0.9.7\lib\site-pa
ckages
curvefem 0.0.0 is already the active version in easy-install.pth

Installed c:\python27\openmdao-0.9.7\lib\site-packages\curvefem-0.0.0-py2.7-win3
2.egg
Processing dependencies for curvefem==0.0.0
Finished processing dependencies for curvefem==0.0.0
```

**Comment by dykesk** [comment]
Hi Evan,

It appears to be deleting the directory? or the directory was never properly created in the first place?

Have you tried installing precomp separately from rotorse? Build it and install directly into your python site-packages?

I’d give that a go.

**Comment by evan-gaertner** [comment]
I never did resolve this and I'm again trying to use precomp and pBEAM.  I discovered today that _precomp and _pBEAM import when the OpenMDAO virtual environment is not active, but generate that DLL load failure error with the virtual environment is active.  

Any thoughts? My OpenMDAO install seems fine, it passes all tests with 2 skips.

**Comment by evan-gaertner** [comment]
The problem was when the OpenMDAO environment was active, '.\openmdao-0.9.7\Scripts' was at the start of my $PATH search order.  There was a compatibility issue with one or more of the .dll's in Scripts.  By removing them all, working dlls were loaded from other directories.
