### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#372]
Hi,

I updated the last WISDEM to the lastest version this time.
but, when I run the blade optimization example (BAR_USC), the error is occurred like this:
```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 168, in run_wisdem
    wt_opt.run_driver()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 753, in run_driver
    return self.driver.run()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 532, in run
    self._reraise()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 778, in _reraise
    raise self._exc_info[1].with_traceback(self._exc_info[2])
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 700, in _gradfunc
    grad = self._compute_totals(of=self._obj_and_nlcons, wrt=self._dvlist,
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\utils\hooks.py", line 119, in execute_hooks
    _run_hooks(post_hooks, inst)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\utils\hooks.py", line 92, in _run_hooks
    hook(inst, **kwargs)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\utils\reports_system.py", line 307, in run_scaling_report_inner
    prob.driver.scaling_report(outfile=scaling_filepath, show_browser=False)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\driver.py", line 1131, in scaling_report
    return view_driver_scaling(self, outfile=outfile, show_browser=show_browser, jac=jac,
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\visualization\scaling_viewer\scaling_report.py", line 456, in view_driver_scaling
    d3_src = f.read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 101885: illegal multibyte sequence
```
the optimization example is run at first time, but few later, the error is occurred.
How can I solve this?

**Comment by gbarter** [comment]
I think this error might be due to an external library, try `conda install openmdao==3.16`

**Comment by SeongwooCheon** [comment]
thank you! I solve this problem.

but, I have an another problem.

After optimization, the error is occurred like this:

```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 175, in run_wisdem
    wt_initial.write_ontology(wt_opt, froot_out)
  File "c:\users\chsu\wisdem\wisdem\glue_code\gc_LoadInputs.py", line 856, in write_ontology
    if wt_opt["blade.internal_structure_2d_fem.definition_layer"][i] < 7:
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 403, in __getitem__
    return self.get_val(name, get_remote=None)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 447, in get_val
    raise RuntimeError(f"{self.model.msginfo}: Variable '{name}' is not local to "
RuntimeError: <model> <class WindPark>: Variable 'blade.internal_structure_2d_fem.definition_layer' is not local to rank 0. You can retrieve values from other processes using `get_val(<name>, get_remote=True)`.
```

How can I solve this?

**Comment by gbarter** [comment]
The MPI error is also an `openmdao` error that should be fixed by using v3.16 as described above.  Let us know if you still have this error even after making this change.

**Comment by SeongwooCheon** [comment]
when I run the IEA-15-240-RWT example, I get the message like this:
```
[00mPerformanceWarning: c:\users\chsu\wisdem\wisdem\drivetrainse\generator_models.py:106
DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`[00m[00mPerformanceWarning: c:\users\chsu\wisdem\wisdem\drivetrainse\generator_models.py:106
```

Can I ignore this?

**Comment by gbarter** [comment]
Yes, you can ignore that.
