### ISSUE TITLE
Sea_depth might be broken

### ISSUE THREAD

**Issue by kevybear** [WISDEM/WISDEM#39]
When running lcoe_csm_assembly.py and if you change the sea_depth parameter >= 30 it fails with the error:
`(openmdao-0.10.3.2) C:\fusedwind-gui\src\wisdem\src\wisdem\lcoe>python lcoe_csm_assembly.py

Traceback (most recent call last):
  File "lcoe_csm_assembly.py", line 257, in <module>
    example()
  File "lcoe_csm_assembly.py", line 237, in example
    lcoe.run()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\component.py", line 557, in run
    self.execute()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\assembly.py", line 769, in execute
    self.driver.run(ffd_order=self.ffd_order, case_uuid=self._case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 312, in run
    super(Driver, self).run(ffd_order, case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\component.py", line 557, in run
    self.execute()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 336, in execute
    self.run_iteration()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 367, in run_iteration
    wf.run(ffd_order=self.ffd_order)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\workflow.py", line 141, in run
    comp.run(ffd_order=ffd_order, case_uuid=case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\component.py", line 557, in run
    self.execute()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\assembly.py", line 769, in execute
    self.driver.run(ffd_order=self.ffd_order, case_uuid=self._case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 312, in run
    super(Driver, self).run(ffd_order, case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\component.py", line 557, in run
    self.execute()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 336, in execute
    self.run_iteration()
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\driver.py", line 367, in run_iteration
    wf.run(ffd_order=self.ffd_order)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\workflow.py", line 141, in run
    comp.run(ffd_order=ffd_order, case_uuid=case_uuid)
  File "c:\openmdao-0.10.3.2\lib\site-packages\openmdao.main-0.10.3.2-py2.7.egg\openmdao\main\component.py", line 557, in run
    self.execute()
  File "c:\fusedwind-gui\src\plant-costsse\src\plant_costsse\nrel_csm_bos\nrel_csm_bos.py", line 213, in execute
    transportation_costs = self.turbTrans + self.supportTrans
AttributeError: 'bos_csm_component' object has no attribute 'turbTrans'`

**Comment by kilojoules** [comment]
Solved in dd0650bc481a6da11e974d433a226831a194e0d4
