### ISSUE TITLE
Question about tower outer diameter

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#392]
Hello.

I tried to increase the outer diameter of the tower of IEA 15MW RWT; from 10m to 15m.
The diameter is the point where the tower and monopile meet.

However, when I run WISDEM,  the error occurs like this:

```
ORBIT library intialized at 'c:\users\chsu\wisdem\wisdem\library'
Traceback (most recent call last):
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\scour_protection_install\standard.py", line 232, in load_material
    vessel.rock_storage.put(mass)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\simpy\resources\container.py", line 29, in __init__
    raise ValueError(f'amount(={amount}) must be > 0.')
ValueError: amount(=0) must be > 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\scour_protection_install\standard.py", line 169, in install_scour_protection
    yield load_material(vessel, vessel.rock_storage.available_capacity, **kwargs)
ValueError: amount(=0) must be > 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2199, in _call_user_function
    yield
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "c:\users\chsu\wisdem\wisdem\orbit\api\wisdem.py", line 440, in compute
    project.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 151, in run
    self.run_multiple_phases_overlapping(install_phases, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 606, in run_multiple_phases_overlapping
    _, logs = self.run_install_phase(name, start, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 476, in run_install_phase
    phase.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\install_phase.py", line 103, in run
    self.env.run(until=until)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 142, in run
    self.step()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 243, in step
    raise exc
ValueError: amount(=0) must be > 0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 170, in run_wisdem
    wt_opt.run_model()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 682, in run_model
    self.model.run_solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 3903, in run_solve_nonlinear
    self._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2560, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 42, in solve
    self._gs_iter()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 760, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2560, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 42, in solve
    self._gs_iter()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 760, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 284, in _solve_nonlinear
    self._compute_wrapper()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2205, in _call_user_function
    raise err_type(
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2199, in _call_user_function
    yield
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "c:\users\chsu\wisdem\wisdem\orbit\api\wisdem.py", line 440, in compute
    project.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 151, in run
    self.run_multiple_phases_overlapping(install_phases, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 606, in run_multiple_phases_overlapping
    _, logs = self.run_install_phase(name, start, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 476, in run_install_phase
    phase.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\install_phase.py", line 103, in run
    self.env.run(until=until)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 142, in run
    self.step()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 243, in step
    raise exc
ValueError: 'orbit.orbit' <class OrbitWisdem>: Error calling compute(), amount(=0) must be > 0.
```

but, when I modified it from 10m to 11m, this error did not occur.

Thank you

**Comment by gbarter** [comment]
Hi @SeongwooCheon .  You have likely exceeded a vessel limit either in mass or deck space of your design.  ORBIT, unfortunately, does not always give helpful error messages when that occurs.  Depending on the analysis you were doing, this may either be enlightening or frustrating to know this.  

If you want to post your input files here, I could take a look.  We might have to enlist the help of the ORBIT team if I cannot find the error.

**Comment by SeongwooCheon** [comment]
Thank you for your response.
Here is my input file.

[input.zip](https://github.com/WISDEM/WISDEM/files/9525330/input.zip)

**Comment by gbarter** [comment]
This file ran fine for me using the `develop` branch of WISDEM.  Please give that a try.

**Comment by SeongwooCheon** [comment]
sorry, I uploaded another input file.
Here is the input file.

[input.zip](https://github.com/WISDEM/WISDEM/files/9553289/input.zip)

**Comment by gbarter** [comment]
This one also ran fine for me. . .

**Comment by gbarter** [comment]
Be sure to do `git checkout develop` and then `git pull`

**Comment by SeongwooCheon** [comment]
I did the update as you suggested, but I got the same error.
It runs well in the analysis process, but I think errors occur in printing the results.

```
NL: NLBGS Converged
ORBIT library intialized at 'c:\users\chsu\wisdem\wisdem\library'
Traceback (most recent call last):
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\scour_protection_install\standard.py", line 232, in load_material
    vessel.rock_storage.put(mass)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\simpy\resources\container.py", line 29, in __init__
    raise ValueError(f'amount(={amount}) must be > 0.')
ValueError: amount(=0) must be > 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\scour_protection_install\standard.py", line 169, in install_scour_protection
    yield load_material(vessel, vessel.rock_storage.available_capacity, **kwargs)
ValueError: amount(=0) must be > 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2199, in _call_user_function
    yield
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "c:\users\chsu\wisdem\wisdem\orbit\api\wisdem.py", line 440, in compute
    project.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 151, in run
    self.run_multiple_phases_overlapping(install_phases, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 606, in run_multiple_phases_overlapping
    _, logs = self.run_install_phase(name, start, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 476, in run_install_phase
    phase.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\install_phase.py", line 103, in run
    self.env.run(until=until)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 142, in run
    self.step()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 243, in step
    raise exc
ValueError: amount(=0) must be > 0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 170, in run_wisdem
    wt_opt.run_model()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 682, in run_model
    self.model.run_solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 3903, in run_solve_nonlinear
    self._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2560, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 42, in solve
    self._gs_iter()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 760, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\group.py", line 2560, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\nonlinear\nonlinear_runonce.py", line 42, in solve
    self._gs_iter()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\solvers\solver.py", line 760, in _gs_iter
    subsys._solve_nonlinear()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 284, in _solve_nonlinear
    self._compute_wrapper()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2205, in _call_user_function
    raise err_type(
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 2199, in _call_user_function
    yield
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\explicitcomponent.py", line 258, in _compute_wrapper
    self.compute(*args)
  File "c:\users\chsu\wisdem\wisdem\orbit\api\wisdem.py", line 440, in compute
    project.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 151, in run
    self.run_multiple_phases_overlapping(install_phases, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 606, in run_multiple_phases_overlapping
    _, logs = self.run_install_phase(name, start, **kwargs)
  File "c:\users\chsu\wisdem\wisdem\orbit\manager.py", line 476, in run_install_phase
    phase.run()
  File "c:\users\chsu\wisdem\wisdem\orbit\phases\install\install_phase.py", line 103, in run
    self.env.run(until=until)
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 142, in run
    self.step()
  File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\_simpy\core.py", line 243, in step
    raise exc
ValueError: 'orbit.orbit' <class OrbitWisdem>: Error calling compute(), amount(=0) must be > 0.
```

**Comment by gbarter** [comment]
This is a tough spot if I cannot recreate your error.  I think I have seen this ORBIT error before, but it should be corrected in the newest versions.  Maybe try a fresh installation with a fresh checkout in a new conda environment.

**Comment by SeongwooCheon** [comment]
Thank you for your response.
I solved this problem.
