### ISSUE TITLE
ERROR: Package 'wisdem' requires a different Python: 3.7.15 not in '>=3.8'

### ISSUE THREAD

**Issue by mftatfcyclone** [WISDEM/WISDEM#403]
I am try to install the new version of WISDEM on my python version  3.7.15 but I could due the following error
ERROR: Package 'wisdem' requires a different Python: 3.7.15 not in '>=3.8'

I used the following command to install the WISDEM package on Linux
pip install git+https://github.com/WISDEM/WISDEM.git

Last week, my code was installed smoothly with the previous version of WISDEM.
What should I do to solve this problem?

**Comment by rdamiani** [comment]
Hi,
I had to reinstall wisdem after a hardware issue, and now when I launch the test, the process hangs indefinitely (seemingly at ccblade):

`(wisdem-env) D:\WISDEM\test>python test_all.py
ORBIT library intialized at 'D:\WISDEM\wisdem\test\test_orbit\data\library'
======================================================== test session starts =========================================================
platform win32 -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\WISDEM
collected 1332 items

..\wisdem\test\test_airfoilprep\test_airfoilprep.py .............                                                               [  0%]
..\wisdem\test\test_ccblade\test_ccblade.py`

By issuins `ctrl+c`, i can interrupt the process and this is what I see  
`========================================================== warnings summary ==========================================================
..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\components\exec_comp.py:7
..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\components\exec_comp.py:7
  DeprecationWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\components\exec_comp.py:7
  `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\components\external_code_comp.py:6
  DeprecationWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\components\external_code_comp.py:6


    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html

..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\surrogate_models\response_surface.py:7
  DeprecationWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\surrogate_models\response_surface.py:7
  The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.

..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pyDOE2\doe_factorial.py:16
  DeprecationWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pyDOE2\doe_factorial.py:16
  the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

..\wisdem\moorpy\system.py:14
  DeprecationWarning: d:\wisdem\wisdem\moorpy\system.py:14
  Please use `MatrixRankWarning` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.eigen` namespace is deprecated.

..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\test_suite\components\expl_comp_array.py:29
  PytestCollectionWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\test_suite\components\expl_comp_array.py:29
  cannot collect test class 'TestExplCompArrayDense' because it has a __init__ constructor (from: wisdem/test/test_optimization_drivers/test_nlopt_driver.py)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================= 13 passed, 7 warnings in 391.11s (0:06:31) =============================================
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 112, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 339, in from_call
    result: Optional[TResult] = func()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\runner.py", line 167, in pytest_runtest_call
    item.runtest()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\_pytest\unittest.py", line 330, in runtest
    self._testcase(result=self)  # type: ignore[arg-type]
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\unittest\case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\unittest\case.py", line 587, in run
    self._callSetUp()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\unittest\case.py", line 546, in _callSetUp
    self.setUp()
  File "D:\WISDEM\wisdem\test\test_ccblade\test_ccblade.py", line 104, in setUp
    airfoil_types[0] = afinit(path.join(basepath, "Cylinder1.dat"))
  File "d:\wisdem\wisdem\ccblade\ccblade.py", line 109, in initFromAerodynFile
    af = Airfoil.initFromAerodynFile(aerodynFile)
  File "d:\wisdem\wisdem\airfoilprep\airfoilprep.py", line 563, in initFromAerodynFile
    junk=f.readline()
  File "D:\ProgramData\Anaconda3\envs\wisdem-env\lib\encodings\cp1252.py", line 22, in decode
    def decode(self, input, final=False):
KeyboardInterrupt'




Any clues on what might be happening and how to fix it?
Thank you!

**Comment by gbarter** [comment]
Hi Rick- I don't see any errors from the output that you copied over.  I just tried a new conda environment and WISDEM install on Windows and it seemed to work and pass (almost) all of the tests.

**Comment by rdamiani** [comment]
Thanks for checking Garrett and Happy TG! 
At this point I will ignore the issue, though it is unsettling that it does not work on my end, i tried with two new installs and i get the same behavior. I can only see this `..\..\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\test_suite\components\expl_comp_array.py:29
  PytestCollectionWarning: D:\ProgramData\Anaconda3\envs\wisdem-env\lib\site-packages\openmdao\test_suite\components\expl_comp_array.py:29
  cannot collect test class 'TestExplCompArrayDense' because it has a __init__ constructor (from: wisdem/test/test_optimization_drivers/test_nlopt_driver.py)` 

that seems a bit more serious than the other (presumably) warnings, but I am not sure that is why the process just hangs. 
It is also interesting that after the Keyboard Interrupt (`ctrl+c`), it spits out a bit of information (warning and pass counts) that seems to be held in a cache and not sent to the standard output/screen.
