### ISSUE TITLE
Error installing WISDEM on windows

### ISSUE THREAD

**Issue by claudius111** [WISDEM/WISDEM#407]
## Description
Hi！
I followed the steps from the guidance https://github.com/WISDEM/WISDEM  to install wisdem on anaconda. 
However, the error was happened when the work was tried to read the fortran files. And the error info shows like the decoding error.  

### Current behavior
~~~
Reading fortran codes...
      Traceback (most recent call last):
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\f2py\crackfortran.py", line 393, in readfortrancode
          l = fin.readline()
              ^^^^^^^^^^^^^^
        File "F:\anaconda3\envs\wisdem-env\Lib\fileinput.py", line 292, in readline
          line = self._readline()
                 ^^^^^^^^^^^^^^^^
        File "F:\anaconda3\envs\wisdem-env\Lib\fileinput.py", line 372, in _readline
          return self._readline()
                 ^^^^^^^^^^^^^^^^
        File "F:\anaconda3\envs\wisdem-env\Lib\encodings\ascii.py", line 26, in decode
          return codecs.ascii_decode(input, self.errors)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 6993: ordinal not in range(128)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "F:\anaconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "F:\anaconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\anaconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 29, in <module>
          setup(
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\core.py", line 169, in setup
          return old_setup(**new_attr)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\anaconda3\envs\wisdem-env\Lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "F:\anaconda3\envs\wisdem-env\Lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "F:\anaconda3\envs\wisdem-env\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\command\egg_info.py", line 24, in run
          self.run_command("build_src")
        File "F:\anaconda3\envs\wisdem-env\Lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "F:\anaconda3\envs\wisdem-env\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\command\build_src.py", line 144, in run
          self.build_sources()
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\command\build_src.py", line 161, in build_sources
          self.build_extension_sources(ext)
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\command\build_src.py", line 321, in build_extension_sources
          sources = self.f2py_sources(sources, ext)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\distutils\command\build_src.py", line 562, in f2py_sources
          numpy.f2py.run_main(f2py_options + ['--lower',
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\f2py\f2py2e.py", line 441, in run_main
          postlist = callcrackfortran(files, options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\f2py\f2py2e.py", line 342, in callcrackfortran
          postlist = crackfortran.crackfortran(files)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\f2py\crackfortran.py", line 3298, in crackfortran
          readfortrancode(files, crackline)
        File "C:\Users\MSI\AppData\Local\Temp\pip-build-env-6bwnm97f\overlay\Lib\site-packages\numpy\f2py\crackfortran.py", line 395, in readfortrancode
          raise Exception(
      Exception: readfortrancode: reading wisdem\rotorse\PreCompPy.f90#0 failed with
      'ascii' codec can't decode byte 0xce in position 6993: ordinal not in range(128).
      It is likely that installing chardet package will help f2py determine the input file encoding correctly.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

~~~
### Code versions
- platform : win-64
- user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.19045

**Comment by gbarter** [comment]
I started seeing this error in other repos recently too.  I did find a non-ascii character in one of the fortran files and removed it.  Are you comfortable switching to the `meson` feature branch to give that a shot?  I'm working on a more current build system that what is in the main branch.   You may encounter other challenges though (just a heads up).

**Comment by mftatfcyclone** [comment]
I have the same error on Linux Manjaro Platform

**Comment by claudius111** [comment]
> I started seeing this error in other repos recently too. I did find a non-ascii character in one of the fortran files and removed it. Are you comfortable switching to the `meson` feature branch to give that a shot? I'm working on a more current build system that what is in the main branch. You may encounter other challenges though (just a heads up).

Ok. Thank you for your reply！I will try it.

**Comment by gbarter** [comment]
The issues here are resolved on the WISDEM `develop` branch.  From the command line in the directory where you downloaded WISDEM, please do:
```
git checkout develop
git pull
```
And give it another shot.

**Comment by clun1** [comment]
i have the same problem as follow
<img width="716" alt="image" src="https://user-images.githubusercontent.com/93849049/231049575-3c09b3be-d85c-4fac-b2f7-271fc281f8a5.png">
how to solve this problem, looking forward your reply

**Comment by clun1** [comment]
and my anaconda information as follow:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/93849049/231051577-103f0b56-2b70-4c5f-a590-896cc3a7f044.png">

**Comment by gbarter** [comment]
It looks like you misspelled the channel name by using `conda-forg` instead of `conda-forge`.  I suggest doing:
```
conda config --remove channels conda-forg
conda config --add channels conda-forge
```

**Comment by clun1** [comment]
thank for your help,now i can download this software,I really appreciate that!

**Comment by clun1** [comment]
i have a new problem,when i want run wisdem, but wisdem could not be identified
<img width="817" alt="image" src="https://user-images.githubusercontent.com/93849049/231203176-81fd81fa-0b47-4174-84c4-0ac86eca78ea.png">
and is there a tutorial for using wisdem?

**Comment by ptrbortolotti** [comment]
the online documentation is the best place to start

https://wisdem.readthedocs.io/en/latest/
