### ISSUE TITLE
nrel5mw.py error problem in the 02_reference_turbines folder

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#421]
Hello.

When I run nrel5mw.py in the 02_reference_turbines folder, I get an error like this.
How can I fix this error?

```
Traceback (most recent call last):
  File "/home/default/WISDEM/examples/02_reference_turbines/nrel5mw_driver.py", line 12, in <module>
    wt_opt, analysis_options, opt_options = run_wisdem(fname_wt_input, fname_modeling_options, fname_analysis_options)
  File "/home/default/WISDEM/wisdem/glue_code/runWISDEM.py", line 122, in run_wisdem
    wt_opt.setup()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openmdao/core/problem.py", line 954, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openmdao/core/system.py", line 1474, in _setup
    self._setup_procs(self.pathname, comm, mode, self._problem_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openmdao/core/group.py", line 595, in _setup_procs
    subsys._setup_procs(subsys.pathname, sub_comm, mode, prob_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openmdao/core/group.py", line 595, in _setup_procs
    subsys._setup_procs(subsys.pathname, sub_comm, mode, prob_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openmdao/core/component.py", line 218, in _setup_procs
    self.setup()
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/landbosse.py", line 57, in setup
    self.setup_discrete_inputs_that_are_dataframes()
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/landbosse.py", line 223, in setup_discrete_inputs_that_are_dataframes
    default_project_data = OpenMDAODataframeCache.read_all_sheets_from_xlsx("ge15_public")
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/OpenMDAODataframeCache.py", line 84, in read_all_sheets_from_xlsx
    xlsx = pd.ExcelFile(xlsx_filename, engine="openpyxl")
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 557, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 545, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 568, in load_workbook
    return load_workbook(
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
    reader.read()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 303, in read
    self.parser.assign_names()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.10/site-packages/openpyxl/reader/workbook.py", line 109, in assign_names
    sheet.defined_names[name] = defn
AttributeError: 'ReadOnlyWorksheet' object has no attribute 'defined_names'

```

**Comment by gbarter** [comment]
Hi Seongwoo,

This is an error with an upstream library.  We [fixed this temporarily](https://github.com/WISDEM/WISDEM/commit/6c9e3df79e8ef415f3960def3786552a9bafc767) in the develop-branch by downgrading `openpyxl` to version 3.1.0.
