### ISSUE TITLE
WISDEM Example 03_blade - analysis_options_aero

### ISSUE THREAD

**Issue by joowandon** [WISDEM/WISDEM#427]
## Description

Hello, 

Errors that seems to be related to PreCompe appeared during testing of 03_blade example. 

Thank you in advance for your kind support. 

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. Installed WISDEM with 'develop' branch instruction 
2. Goto to Examples/03_blade 
3. Try 'python blade_driver.py' 

### Current behavior
…
Traceback (most recent call last):
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/system.py", line 2958, in _call_user_function
    yield
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 291, in _compute_wrapper
    self.compute(self._inputs, self._outputs,
  File "/root/GitHub/WISDEM/wisdem/rotorse/rotor_elasticity.py", line 754, in compute
    ) = beam.sectionProperties()
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GitHub/WISDEM/wisdem/rotorse/precomp.py", line 188, in sectionProperties
    results = _precomp.properties(
              ^^^^^^^^^^^^^^^^^^^^
**ValueError: _precomp._precomp.precomp.properties: failed to create array from the 26th argument `n_laminaw` -- 0-th dimension must be fixed to 1 but got 2**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/GitHub/WISDEM/examples/03_blade/blade_driver.py", line 16, in <module>
    wt_opt, modeling_options, analysis_options = run_wisdem(fname_wt_input, fname_modeling_options, fname_analysis_options_aero)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GitHub/WISDEM/wisdem/glue_code/runWISDEM.py", line 179, in run_wisdem
    wt_opt.run_driver()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/problem.py", line 686, in run_driver
    return self.driver.run()
           ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/drivers/scipy_optimizer.py", line 548, in run
    self._reraise()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/drivers/scipy_optimizer.py", line 794, in _reraise
    raise self._exc_info[1].with_traceback(self._exc_info[2])
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/drivers/scipy_optimizer.py", line 716, in _gradfunc
    grad = self._compute_totals(of=self._obj_and_nlcons, wrt=self._dvlist,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/driver.py", line 991, in _compute_totals
    totals = total_jac.compute_totals_approx()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/total_jac.py", line 1520, in compute_totals_approx
    model._linearize(model._assembled_jac,
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 2734, in _linearize
    approximation.compute_approximations(self, jac=jac)
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/approximation_scheme.py", line 530, in compute_approximations
    for ic, col in self.compute_approx_col_iter(system,
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/finite_difference.py", line 258, in compute_approx_col_iter
    yield from self._compute_approx_col_iter(system, under_cs=under_cs)
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/approximation_scheme.py", line 544, in _compute_approx_col_iter
    yield from self._uncolored_column_iter(system, approx_groups)
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/approximation_scheme.py", line 458, in _uncolored_column_iter
    result = self._run_point(system, [(vec, vecidxs)],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/finite_difference.py", line 359, in _run_point
    results = self._run_sub_point(system, idx_info, delta, total, idx_start=idx_start,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/approximation_schemes/finite_difference.py", line 410, in _run_sub_point
    system.run_solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/system.py", line 4678, in run_solve_nonlinear
    self._solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 2534, in _solve_nonlinear
    self._nonlinear_solver._solve_with_cache_check()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 26, in _solve_with_cache_check
    self.solve()  # don't use caching
    ^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 45, in solve
    self._gs_iter()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 793, in _gs_iter
    subsys._solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 2534, in _solve_nonlinear
    self._nonlinear_solver._solve_with_cache_check()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 831, in _solve_with_cache_check
    self.solve()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 589, in solve
    raise err
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 585, in solve
    self._solve()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 629, in _solve
    norm0, norm = self._iter_initialize()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_block_gs.py", line 109, in _iter_initialize
    return super()._iter_initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 608, in _iter_initialize
    self._run_apply()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_block_gs.py", line 241, in _run_apply
    subsys._solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 2534, in _solve_nonlinear
    self._nonlinear_solver._solve_with_cache_check()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 26, in _solve_with_cache_check
    self.solve()  # don't use caching
    ^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 45, in solve
    self._gs_iter()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 793, in _gs_iter
    subsys._solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 2534, in _solve_nonlinear
    self._nonlinear_solver._solve_with_cache_check()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 26, in _solve_with_cache_check
    self.solve()  # don't use caching
    ^^^^^^^^^^^^
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 45, in solve
    self._gs_iter()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/solvers/solver.py", line 793, in _gs_iter
    subsys._solve_nonlinear()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 320, in _solve_nonlinear
    self._compute_wrapper()
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 274, in _compute_wrapper
    with self._call_user_function('compute'):
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/system.py", line 2964, in _call_user_function
    raise err_type(
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/system.py", line 2958, in _call_user_function
    yield
  File "/root/miniconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 291, in _compute_wrapper
    self.compute(self._inputs, self._outputs,
  File "/root/GitHub/WISDEM/wisdem/rotorse/rotor_elasticity.py", line 754, in compute
    ) = beam.sectionProperties()
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GitHub/WISDEM/wisdem/rotorse/precomp.py", line 188, in sectionProperties
    results = _precomp.properties(
              ^^^^^^^^^^^^^^^^^^^^
ValueError: 'wt.rotorse.re.precomp' <class RunPreComp>: Error calling compute(), _precomp._precomp.precomp.properties: failed to create array from the 26th argument `n_laminaw` -- 0-th dimension must be fixed to 1 but got 2

### Expected behavior
No Error

### Code versions
- platform : linux-64 (Ubutu)
- user-agent : conda/23.3.0 requests/2.28.1 CPython/3.10.9 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35
- python version : 3.10.9.final.0

**Comment by joowandon** [comment]
Hello, 
The precome related errors were solved by increasing number of control point of aero_shape (twist, chord). 
The issue is resolved, but it would be nice to know the underlying reason. 

----------------analysis_options_aero.yaml -----------------------------------------------------------------------------
        aero_shape:
            twist:
                flag: True  # Flag to optimize the twist
                inverse: False # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
                _n_opt: 8_     # Number of control points along blade span
                max_decrease: 0.08722222222222221 # Maximum decrease for the twist in [rad] at the n_opt locations
                max_increase: 0.08722222222222221 # Maximum increase for the twist in [rad] at the n_opt locations
                index_start: 2 # Lock the first two DVs from blade root
                index_end: 4 # All DVs close to blade tip are active
            chord:
                flag: True  # Flag to optimize the chord
                _n_opt: 8_     # Number of control points along blade span
                max_decrease: 0.3 # Minimum multiplicative gain on existing chord at the n_opt locations
                max_increase: 3. # Maximum multiplicative gain on existing chord at the n_opt locations
                index_start: 0 # Start by optimizing chord at blade root
                index_end: 3 # Lock chord at blade tip
-----------------------------------------------------------------------------------------------------------------------

Thanks
