### ISSUE TITLE
Why can't I run'example_from_yaml'

### ISSUE THREAD

**Issue by junjihan** [WISDEM/WISDEM#429]
Sincere greetings to you!
Perhaps I started to study python in few days, I don't  know why can't I run 'example_from_yaml', I have installed all  of the prerequisites, When I click 'Run example_from_yaml', it will show the warnnings as follow. (It told me that 'No module named 'ccblade'', But I found ccblade was in'C:\Users\handynasty\Downloads\WISDEM-master\WISDEM-master\wisdem\ccblade' ,But I remember I have successfully installed WISDEM.)

C:\Users\handynasty\PycharmProjects\pythonProject\venv\Scripts\python.exe C:\Users\handynasty\Downloads\RAFT-master\RAFT-master\examples\example_from_yaml.py 
Traceback (most recent call last):
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\raft-0.1-py3.11.egg\raft\raft_rotor.py", line 18, in <module>
    from ccblade.ccblade import CCBlade, CCAirfoil
ModuleNotFoundError: No module named 'ccblade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\handynasty\Downloads\RAFT-master\RAFT-master\examples\example_from_yaml.py", line 6, in <module>
    import raft
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\raft-0.1-py3.11.egg\raft\__init__.py", line 3, in <module>
    import raft.raft_model as model
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\raft-0.1-py3.11.egg\raft\raft_model.py", line 15, in <module>
    import raft.raft_fowt  as fowt
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\raft-0.1-py3.11.egg\raft\raft_fowt.py", line 11, in <module>
    from raft.raft_rotor import Rotor
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\raft-0.1-py3.11.egg\raft\raft_rotor.py", line 20, in <module>
    from wisdem.ccblade.ccblade import CCBlade, CCAirfoil
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\__init__.py", line 1, in <module>
    from wisdem.glue_code.runWISDEM import run_wisdem
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\glue_code\runWISDEM.py", line 11, in <module>
    from wisdem.glue_code.glue_code import WindPark
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\glue_code\glue_code.py", line 4, in <module>
    from wisdem.rotorse.rotor import RotorSE
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\rotorse\rotor.py", line 4, in <module>
    from wisdem.rotorse.rotor_power import RotorPower, NoStallConstraint
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\rotorse\rotor_power.py", line 16, in <module>
    from wisdem.ccblade.ccblade import CCBlade, CCAirfoil
  File "C:\Users\handynasty\PycharmProjects\pythonProject\venv\Lib\site-packages\wisdem-3.8-py3.11.egg\wisdem\ccblade\ccblade.py", line 31, in <module>
    import wisdem.ccblade._bem as _bem
ModuleNotFoundError: No module named 'wisdem.ccblade._bem'

Process finished with exit code 1

**Comment by gbarter** [comment]
That error means that WISDEM did not install successfully.  You can post the errors from the install steps.  I would suggset just doing `conda install wisdem` and then proceeding with the examples and tutorials

**Comment by junjihan** [comment]
> 该错误意味着 WISDEM 未成功安装。您可以发布安装步骤中的错误。我会建议只做，然后继续示例和教程`conda install wisdem`

Thanks, it is only useful in Anaconda? I use pycharm as compiler, if pycharm is available, how can I install WISDEM?

**Comment by gbarter** [comment]
PyCharm is an IDE, not a compiler.  You would still need Fortran and C compilers on your system.  The easiest and most managed way to do that is to use Anaconda.

**Comment by junjihan** [comment]
> PyCharm is an IDE, not a compiler. You would still need Fortran and C compilers on your system. The easiest and most managed way to do that is to use Anaconda.

Jesus, I understand now, thanks a lot!
