### ISSUE TITLE
Design variable interpolation method

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#433]
Hello

I think that the design variables along the spanwise are interpolated with interp function which is linear interpolation method with regard to n_span value in the modeling_option.yaml file.

But I want to interpolate optimized values with pchipInterpolation, RBFInterpolation, etc.

should I modify the code below?

https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/glue_code/gc_PoseOptimization.py#L593

https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/rotorse/parametrize_rotor.py#L194

and also, when I update the develop branch, the error is occurred like this:
```

Traceback (most recent call last):
  File "/home/default/anaconda3/envs/wisdem-env/bin/wisdem", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/WISDEM/wisdem/main.py", line 74, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/WISDEM/wisdem/glue_code/runWISDEM.py", line 123, in run_wisdem
    wt_opt.setup()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/problem.py", line 954, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/system.py", line 1474, in _setup
    self._setup_procs(self.pathname, comm, mode, self._problem_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 595, in _setup_procs
    subsys._setup_procs(subsys.pathname, sub_comm, mode, prob_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/group.py", line 595, in _setup_procs
    subsys._setup_procs(subsys.pathname, sub_comm, mode, prob_meta)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openmdao/core/component.py", line 218, in _setup_procs
    self.setup()
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/landbosse.py", line 57, in setup
    self.setup_discrete_inputs_that_are_dataframes()
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/landbosse.py", line 223, in setup_discrete_inputs_that_are_dataframes
    default_project_data = OpenMDAODataframeCache.read_all_sheets_from_xlsx("ge15_public")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/WISDEM/wisdem/landbosse/landbosse_omdao/OpenMDAODataframeCache.py", line 84, in read_all_sheets_from_xlsx
    xlsx = pd.ExcelFile(xlsx_filename, engine="openpyxl")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 549, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 540, in __init__
    self.book = self.load_workbook(self.handles.handle)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 560, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
    reader.read()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openpyxl/reader/excel.py", line 303, in read
    self.parser.assign_names()
  File "/home/default/anaconda3/envs/wisdem-env/lib/python3.11/site-packages/openpyxl/reader/workbook.py", line 109, in assign_names
    sheet.defined_names[name] = defn
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReadOnlyWorksheet' object has no attribute 'defined_names'

```

**Comment by SeongwooCheon** [comment]
as your comment, I do `git pull` and `python setup.py develop`

**Comment by gbarter** [comment]
Hmm.  This is a problem in a third-party library.  Try `conda install openpyxl=3.0.10`

**Comment by SeongwooCheon** [comment]
Thank you. the error no longer occurs.

Is it difficult to implement my first question in the WISDEM?

**Comment by gbarter** [comment]
WISDEM uses pchip interpolation to build the spanwise profiles from the control nodes that are adjusted as design variables.  We do not currently support changing that interpolation scheme.

**Comment by SeongwooCheon** [comment]
And also, I want to check the change of design variable according to process of optimization. To do this, just activate the recoder option in the analysis options yaml file? and can filename extension only be set to sql?

**Comment by ptrbortolotti** [comment]
The recorder is useful to track the progress of the optimizer yes. The format is .sql, and you can generate plots from it by running this script (make sure to point to the right analysis options yaml):

```
import openmdao.api as om
from wisdem.glue_code.gc_RunTools import PlotRecorder
import wisdem.inputs as sch
import os

mydir = os.path.dirname(os.path.realpath(__file__))  # get path to this file
fname_analysis_options = mydir + os.sep + "analysis_options.yaml"
analysis_options = sch.load_analysis_yaml(fname_analysis_options)
wt_opt = om.Problem(model=PlotRecorder(opt_options=analysis_options))
wt_opt.setup(derivatives=False)
wt_opt.run_model()
```

You will find the plots in the output folder
