### ISSUE TITLE
Issue in installation tarfile.ReadError

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#46]
Below is the log generated. (Updated)
All is fine until python tried to install Turbine_CostsSE. Any suggestions on why this is happening.

My environment variable is set to
>  C:\Python27
 
Thanks.

````
(openmdao-0.7.0) C:\Python27\openmdao-0.7.0\WISDEM>python setup_all.py
Searching for pandas
Best match: pandas 0.14.1
pandas 0.14.1 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages
Processing dependencies for pandas
Finished processing dependencies for pandas
Searching for algopy
Best match: algopy 0.5.5
Processing algopy-0.5.5-py2.7.egg
algopy 0.5.5 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\algopy-0.5.5-py2.7.egg
Processing dependencies for algopy
Finished processing dependencies for algopy
Searching for zope.interface
Best match: zope.interface 3.6.1
Processing zope.interface-3.6.1-py2.7-win32.egg
zope.interface 3.6.1 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\zope.interface-3.6.1-py2.7-wi
n32.egg
Processing dependencies for zope.interface
Finished processing dependencies for zope.interface
Searching for sphinx
Best match: sphinx 1.6.3
Processing sphinx-1.6.3-py2.7.egg
sphinx 1.6.3 is already the active version in easy-install.pth
Installing sphinx-apidoc-script.py script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-apidoc.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-apidoc.exe.manifest script to C:\Python27\openmdao-0.7.0\Scrip
ts
Installing sphinx-build-script.py script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-build.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-build.exe.manifest script to C:\Python27\openmdao-0.7.0\Script
s
Installing sphinx-quickstart-script.py script to C:\Python27\openmdao-0.7.0\Scri
pts
Installing sphinx-quickstart.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-quickstart.exe.manifest script to C:\Python27\openmdao-0.7.0\S
cripts
Installing sphinx-autogen-script.py script to C:\Python27\openmdao-0.7.0\Scripts

Installing sphinx-autogen.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing sphinx-autogen.exe.manifest script to C:\Python27\openmdao-0.7.0\Scri
pts

Using c:\python27\openmdao-0.7.0\lib\site-packages\sphinx-1.6.3-py2.7.egg
Processing dependencies for sphinx
Finished processing dependencies for sphinx
Searching for xlrd
Best match: xlrd 1.0.0
Processing xlrd-1.0.0-py2.7.egg
xlrd 1.0.0 is already the active version in easy-install.pth
Installing runxlrd.py script to C:\Python27\openmdao-0.7.0\Scripts

Using c:\python27\openmdao-0.7.0\lib\site-packages\xlrd-1.0.0-py2.7.egg
Processing dependencies for xlrd
Finished processing dependencies for xlrd
Searching for pyopt
Best match: pyopt 0.84
Processing pyopt-0.84-py2.7.egg
pyopt 0.84 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\pyopt-0.84-py2.7.egg
Processing dependencies for pyopt
Finished processing dependencies for pyopt
Searching for py2exe
Best match: py2exe 0.9.2.2
Processing py2exe-0.9.2.2-py2.7-win32.egg
py2exe 0.9.2.2 is already the active version in easy-install.pth
Installing build_exe-script.py script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe-script.pyc script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe.exe.manifest script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe-script.py script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe.exe script to C:\Python27\openmdao-0.7.0\Scripts
Installing build_exe.exe.manifest script to C:\Python27\openmdao-0.7.0\Scripts

Using c:\python27\openmdao-0.7.0\lib\site-packages\py2exe-0.9.2.2-py2.7-win32.eg
g
Processing dependencies for py2exe
Finished processing dependencies for py2exe
Searching for pyzmq
Reading https://pypi.python.org/simple/pyzmq/
Downloading https://pypi.python.org/packages/af/37/8e0bf3800823bc247c36715a52e92
4e8f8fd5d1432f04b44b8cd7a5d7e55/pyzmq-16.0.2.tar.gz#md5=9a8768b00a566a400d70318f
8c359cfe
Best match: pyzmq 16.0.2
Processing pyzmq-16.0.2.tar.gz
Writing c:\users\anur\appdata\local\temp\easy_install-6x9i5o\pyzmq-16.0.2\setup.
cfg
Running pyzmq-16.0.2\setup.py -q bdist_egg --dist-dir c:\users\anur\appdata\loca
l\temp\easy_install-6x9i5o\pyzmq-16.0.2\egg-dist-tmp-fszbbf
warning: no files found matching 'tox.ini'
no previously-included directories found matching 'docs\build'
no previously-included directories found matching 'docs\gh-pages'
warning: no previously-included files found matching 'bundled\zeromq\src\Makefil
e*'
warning: no previously-included files found matching 'bundled\zeromq\src\platfor
m.hpp'
warning: no previously-included files found matching 'zmq\libzmq*'
warning: no previously-included files matching '__pycache__\*' found anywhere in
 distribution
warning: no previously-included files matching '.deps\*' found anywhere in distr
ibution
warning: no previously-included files matching '*.so' found anywhere in distribu
tion
warning: no previously-included files matching '*.pyd' found anywhere in distrib
ution
warning: no previously-included files matching '.git*' found anywhere in distrib
ution
warning: no previously-included files matching '.DS_Store' found anywhere in dis
tribution
warning: no previously-included files matching '.mailmap' found anywhere in dist
ribution
warning: no previously-included files matching 'Makefile.am' found anywhere in d
istribution
warning: no previously-included files matching 'Makefile.in' found anywhere in d
istribution
************************************************
Warning: Couldn't find an acceptable libzmq on the system.

If you expected pyzmq to link against an installed libzmq, please check to make
sure:

    * You have a C compiler installed
    * A development version of Python is installed (including headers)
    * A development version of ZMQ >= 3.2 is installed (including headers)
    * If ZMQ is not in a default location, supply the argument --zmq=<path>
    * If you did recently install ZMQ to a default location,
      try rebuilding the ld cache with `sudo ldconfig`
      or specify zmq's location with `--zmq=/usr/local`

You can skip all this detection/waiting nonsense if you know
you want pyzmq to bundle libzmq as an extension by passing:

    `--zmq=bundled`

I will now try to build libzmq as a Python extension
unless you interrupt me (^C) in the next 10 seconds...

 1...
************************************************
Using bundled libzmq
already have bundled\zeromq
staging platform.hpp from: bundled\zeromq\builds\msvc
************************************************
In file included from zmq\utils/zmq_compat.h:16:0,
                 from zmq\devices\monitoredqueue.c:403:
bundled\zeromq\include/zmq.h:439:52: error: unknown type name 'uint8_t'
 ZMQ_EXPORT char *zmq_z85_encode (char *dest, const uint8_t *data, size_t size);

                                                    ^
bundled\zeromq\include/zmq.h:442:12: error: unknown type name 'uint8_t'
 ZMQ_EXPORT uint8_t *zmq_z85_decode (uint8_t *dest, const char *string);
            ^
bundled\zeromq\include/zmq.h:442:37: error: unknown type name 'uint8_t'
 ZMQ_EXPORT uint8_t *zmq_z85_decode (uint8_t *dest, const char *string);
                                     ^
In file included from zmq\devices\monitoredqueue.c:403:0:
zmq\devices\monitoredqueue.c: In function '__pyx_f_3zmq_7devices_14monitoredqueu
e__relay':
zmq\utils/zmq_compat.h:12:23: error: unknown type name 'int64_t'
 #define pyzmq_int64_t int64_t
                       ^
zmq\devices\monitoredqueue.c:1761:3: note: in expansion of macro 'pyzmq_int64_t'

   pyzmq_int64_t __pyx_v_flag_2;
   ^
zmq\utils/zmq_compat.h:12:23: error: 'int64_t' undeclared (first use in this fun
ction)
 #define pyzmq_int64_t int64_t
                       ^
zmq\devices\monitoredqueue.c:1786:30: note: in expansion of macro 'pyzmq_int64_t
'
     __pyx_v_flagsz = (sizeof(pyzmq_int64_t));
                              ^
zmq\utils/zmq_compat.h:12:23: note: each undeclared identifier is reported only
once for each function it appears in
 #define pyzmq_int64_t int64_t
                       ^
zmq\devices\monitoredqueue.c:1786:30: note: in expansion of macro 'pyzmq_int64_t
'
     __pyx_v_flagsz = (sizeof(pyzmq_int64_t));
                              ^
zmq\devices\monitoredqueue.c: In function '__Pyx_RaiseArgtupleInvalid':
zmq\devices\monitoredqueue.c:5271:18: warning: unknown conversion type character
 'z' in format [-Wformat=]
                  (num_expected == 1) ? "" : "s", num_found);
                  ^
zmq\devices\monitoredqueue.c:5271:18: warning: format '%s' expects argument of t
ype 'char *', but argument 5 has type 'Py_ssize_t' [-Wformat=]
zmq\devices\monitoredqueue.c:5271:18: warning: unknown conversion type character
 'z' in format [-Wformat=]
zmq\devices\monitoredqueue.c:5271:18: warning: too many arguments for format [-W
format-extra-args]
zmq\devices\monitoredqueue.c: In function '__Pyx_CyFunction_CallMethod':
zmq\devices\monitoredqueue.c:6537:17: warning: unknown conversion type character
 'z' in format [-Wformat=]
                 f->m_ml->ml_name, size);
                 ^
zmq\devices\monitoredqueue.c:6537:17: warning: too many arguments for format [-W
format-extra-args]
zmq\devices\monitoredqueue.c:6553:17: warning: unknown conversion type character
 'z' in format [-Wformat=]
                 f->m_ml->ml_name, size);
                 ^
zmq\devices\monitoredqueue.c:6553:17: warning: too many arguments for format [-W
format-extra-args]
zmq\devices\monitoredqueue.c: In function '__Pyx_ImportType':
zmq\devices\monitoredqueue.c:7390:13: warning: unknown conversion type character
 'z' in format [-Wformat=]
             module_name, class_name, basicsize, size);
             ^
zmq\devices\monitoredqueue.c:7390:13: warning: unknown conversion type character
 'z' in format [-Wformat=]
zmq\devices\monitoredqueue.c:7390:13: warning: too many arguments for format [-W
format-extra-args]
zmq\devices\monitoredqueue.c:7396:13: warning: unknown conversion type character
 'z' in format [-Wformat=]
             module_name, class_name, basicsize, size);
             ^
zmq\devices\monitoredqueue.c:7396:13: warning: unknown conversion type character
 'z' in format [-Wformat=]
zmq\devices\monitoredqueue.c:7396:13: warning: too many arguments for format [-W
format-extra-args]
error: Setup script exited with error: command 'c:\\Rtools\\mingw_32\\bin\\gcc.e
xe' failed with exit status 1
Searching for sphinxcontrib-bibtex
Best match: sphinxcontrib-bibtex 0.3.5
Processing sphinxcontrib_bibtex-0.3.5-py2.7.egg
sphinxcontrib-bibtex 0.3.5 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\sphinxcontrib_bibtex-0.3.5-py
2.7.egg
Processing dependencies for sphinxcontrib-bibtex
Finished processing dependencies for sphinxcontrib-bibtex
Searching for sphinxcontrib-napoleon
Best match: sphinxcontrib-napoleon 0.6.1
Processing sphinxcontrib_napoleon-0.6.1-py2.7.egg
sphinxcontrib-napoleon 0.6.1 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\sphinxcontrib_napoleon-0.6.1-
py2.7.egg
Processing dependencies for sphinxcontrib-napoleon
Finished processing dependencies for sphinxcontrib-napoleon
Searching for numpydoc
Best match: numpydoc 0.7.0
Processing numpydoc-0.7.0-py2.7.egg
numpydoc 0.7.0 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\numpydoc-0.7.0-py2.7.egg
Processing dependencies for numpydoc
Finished processing dependencies for numpydoc
Searching for ipython
Reading https://pypi.python.org/simple/ipython/
Downloading https://pypi.python.org/packages/79/63/b671fc2bf0051739e87a7478a207b
beb45cfae3c328d38ccdd063d9e0074/ipython-6.1.0.tar.gz#md5=1e15e1ce3f3f722da6935d7
ac0e51346
Best match: ipython 6.1.0
Processing ipython-6.1.0.tar.gz
Writing c:\users\anur\appdata\local\temp\easy_install-k7ruj5\ipython-6.1.0\setup
.cfg
Running ipython-6.1.0\setup.py -q bdist_egg --dist-dir c:\users\anur\appdata\loc
al\temp\easy_install-k7ruj5\ipython-6.1.0\egg-dist-tmp-tkov77

IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.

Beginning with IPython 6.0, Python 3.3 and above is required.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst

Python sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial
=0) detected.


error: Setup script exited with 1
Searching for python-dateutil
Best match: python-dateutil 2.6.0
Processing python_dateutil-2.6.0-py2.7.egg
python-dateutil 2.6.0 is already the active version in easy-install.pth

Using c:\python27\openmdao-0.7.0\lib\site-packages\python_dateutil-2.6.0-py2.7.e
gg
Processing dependencies for python-dateutil
Finished processing dependencies for python-dateutil
install url: package= fusedwind url=  http://github.com/FUSED-Wind/fusedwind/tar
ball/develop
installing distribution from current directory as a 'develop' egg
running develop
running egg_info
creating src\fusedwind.egg-info
writing requirements to src\fusedwind.egg-info\requires.txt
writing src\fusedwind.egg-info\PKG-INFO
writing top-level names to src\fusedwind.egg-info\top_level.txt
writing dependency_links to src\fusedwind.egg-info\dependency_links.txt
writing manifest file 'src\fusedwind.egg-info\SOURCES.txt'
reading manifest file 'src\fusedwind.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'src\fusedwind\sphinx_build\html'
writing manifest file 'src\fusedwind.egg-info\SOURCES.txt'
running build_ext
Creating c:\python27\openmdao-0.7.0\lib\site-packages\fusedwind.egg-link (link t
o src)
Adding fusedwind 0.1.0 to easy-install.pth file

Installed c:\python27\openmdao-0.7.0\wisdem\plugins\fusedwind\src
subprocess returned  0
install url: package= Turbine_CostsSE url=  http://github.com/WISDEM/Turbine_Cos
tsSE/tarball/0.1
installing distribution from current directory as a 'develop' egg
running develop
running egg_info
creating src\Turbine_CostsSE.egg-info
writing requirements to src\Turbine_CostsSE.egg-info\requires.txt
writing src\Turbine_CostsSE.egg-info\PKG-INFO
writing top-level names to src\Turbine_CostsSE.egg-info\top_level.txt
writing dependency_links to src\Turbine_CostsSE.egg-info\dependency_links.txt
writing manifest file 'src\Turbine_CostsSE.egg-info\SOURCES.txt'
reading manifest file 'src\Turbine_CostsSE.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src\Turbine_CostsSE.egg-info\SOURCES.txt'
running build_ext
Creating c:\python27\openmdao-0.7.0\lib\site-packages\Turbine-CostsSE.egg-link (
link to src)
Adding Turbine-CostsSE 0.1.0 to easy-install.pth file

Installed c:\python27\openmdao-0.7.0\wisdem\plugins\turbine_costsse\src
subprocess returned  0
install url: package= CommonSE url=  http://github.com/WISDEM/CommonSE/tarball/0
.1
Traceback (most recent call last):
  File "setup_all.py", line 105, in <module>
    install_url(f, url,force=options.force)
  File "setup_all.py", line 28, in install_url
    thetarfile = tarfile.open(fileobj=response, mode="r|gz")
  File "C:\Python27\Lib\tarfile.py", line 1703, in open
    stream = _Stream(name, filemode, comptype, fileobj, bufsize)
  File "C:\Python27\Lib\tarfile.py", line 430, in __init__
    self._init_read_gz()
  File "C:\Python27\Lib\tarfile.py", line 524, in _init_read_gz
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

(openmdao-0.7.0) C:\Python27\openmdao-0.7.0\WISDEM>
```

**Comment by kilojoules** [comment]
You could try installing Turbine_CostsSE from source. In the activated environment, navigate to https://github.com/WISDEM/Turbine_CostsSE and run `python setup.py install`

**Comment by SamAct** [comment]
That worked should I do the same for all other dependencies? 
Because  `import turbine_costsse.turbine_costsse` is giving me an error.
See below:
```
(openmdao-0.7.0) C:\Python27\openmdao-0.7.0\Turbine_CostsSE>plugin install
installing distribution from current directory as a 'develop' egg
running develop
running egg_info
writing requirements to src\Turbine_CostsSE.egg-info\requires.txt
writing src\Turbine_CostsSE.egg-info\PKG-INFO
writing top-level names to src\Turbine_CostsSE.egg-info\top_level.txt
writing dependency_links to src\Turbine_CostsSE.egg-info\dependency_links.txt
reading manifest file 'src\Turbine_CostsSE.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src\Turbine_CostsSE.egg-info\SOURCES.txt'
running build_ext
Creating c:\python27\openmdao-0.7.0\lib\site-packages\Turbine-CostsSE.egg-link (
link to src)
Removing turbine-costsse 0.1.0 from easy-install.pth file
Adding Turbine-CostsSE 0.1.0 to easy-install.pth file

Installed c:\python27\openmdao-0.7.0\turbine_costsse\src

(openmdao-0.7.0) C:\Python27\openmdao-0.7.0\Turbine_CostsSE>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import turbine_costsse.turbine_costsse

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\openmdao-0.7.0\turbine_costsse\src\turbine_costsse\turbine_c
ostsse.py", line 14, in <module>
    from fusedwind.plant_cost.fused_tcc import FullRotorCostModel, FullRotorCost
Aggregator, FullHubSystemCostAggregator, BaseComponentCostModel, configure_full_
rcc
  File "c:\python27\openmdao-0.7.0\wisdem\plugins\fusedwind\src\fusedwind\plant_
cost\fused_tcc.py", line 7, in <module>
    from fusedwind.interface import base, implement_base
  File "c:\python27\openmdao-0.7.0\wisdem\plugins\fusedwind\src\fusedwind\interf
ace.py", line 5, in <module>
    from openmdao.lib.datatypes.api import Slot, Instance
ImportError: cannot import name Instance
```

**Comment by SamAct** [comment]
Is it because fusedwind in not properly installed? If so I will have to switch to OpenMDAO-10.3.2, the only supporting version for Fusedwind.

**Comment by kilojoules** [comment]
Yes, perhaps the OpenMDAO version is causing the error.

**Comment by SamAct** [comment]
okay just to be sure would you kindly explain step 6 in [WISDEM Installation page](https://github.com/WISDEM/WISDEM) for me. I am not sure I understand it. I have every PATH as it is in 5.

Do I have to edit the file setup.py and add the three codes listed? Anything else?

**Comment by dykesk** [comment]
This issue should have been fixed by using the proper openmdao version
