### ISSUE TITLE
Installation question~~!!

### ISSUE THREAD

**Issue by abc720919** [WISDEM/WISDEM#47]
Dear sir
I have a question about how to run wisdem unit tests successfully:
Microsoft Windows
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jason2>cd "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmd
ao-0.7.0"

C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0>call Script
s\activate.bat
Traceback (most recent call last):
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\Scr
ipts\get_full_libpath-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 3074
, in <module>
    @_call_aside
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 3058
, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 3087
, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 666,
 in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 679,
 in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\setuptools-36.4.0-py2.7.egg\pkg_resources\__init__.py", line 872,
 in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (traits 3.3.0 (c:\users\jason2\desktop\
wisdem-wisdem-0.1-15-ged28592\openmdao-0.7.0\lib\site-packages\traits-3.3.0-py2.
7-win32.egg), Requirement.parse('Traits==4.3.0'), set(['openmdao.util']))

(openmdao-0.7.0) C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-
0.7.0>cd "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\WISDEM\src"

(openmdao-0.7.0) C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\WISDEM\sr
c>python
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wisdem.lcoe.lcoe_csm_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wisdem\lcoe\lcoe_csm_assembly.py", line 10, in <module>
    from fusedwind.plant_cost.fused_finance import ExtendedFinancialAnalysis, co
nfigure_extended_financial_analysis
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\fusedwind-0.1.0-py2.7.egg\fusedwind\plant_cost\fused_finance.py",
 line 6, in <module>
    from fusedwind.plant_flow.asym import BaseAEPModel
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\fusedwind-0.1.0-py2.7.egg\fusedwind\plant_flow\asym.py", line 14,
 in <module>
    from vt import *
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\fusedwind-0.1.0-py2.7.egg\fusedwind\plant_flow\vt.py", line 15, i
n <module>
    import matplotlib.pylab as plt
  File "c:\python27\lib\site-packages\matplotlib\__init__.py", line 121, in <mod
ule>
    '.'.join(str(x) for x in _required)))
ImportError: matplotlib requires pyparsing >= 1.5.6
>>> import wisdem.lcoe.lcoe_se_csm_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lcoe_se_csm_assembly
>>> import wisdem.turbinese.turbine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wisdem\turbinese\turbine.py", line 15, in <module>
    from rotorse.rotor import RotorSE
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\rotorse-0.1.0-py2.7.egg\rotorse\rotor.py", line 15, in <module>
    from rotoraero import SetupRunVarSpeed, RegulatedPowerCurve, AEP, VarSpeedMa
chine, \
  File "C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\openmdao-0.7.0\lib
\site-packages\rotorse-0.1.0-py2.7.egg\rotorse\rotoraero.py", line 12, in <modul
e>
    from openmdao.main.api import VariableTree, Component, Assembly, ImplicitCom
ponent
ImportError: cannot import name ImplicitComponent

>>> ^Z

(openmdao-0.7.0) C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\WISDEM\sr
c>python test/test_WISDEM.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

(openmdao-0.7.0) C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\WISDEM\sr
c>python test/test_turbine_gradients.py
Traceback (most recent call last):
  File "test/test_turbine_gradients.py", line 13, in <module>
    from wisdem.turbinese.turbine import MaxTipDeflection
ImportError: No module named wisdem.turbinese.turbine

(openmdao-0.7.0) C:\Users\jason2\Desktop\WISDEM-WISDEM-0.1-15-ged28592\WISDEM\sr
c>

Thanks for your help.

**Comment by dykesk** [comment]
It looks like there is an issue with your installation since it is not finding the wisdem python packages. This is not a code issue - closing.
