### ISSUE TITLE
cobyla.cobyla error 

### ISSUE THREAD

**Issue by michaelXDzhang** [WISDEM/WISDEM#49]
I install all until running unit test get following error, need help!
>>> import wisdem.lcoe.lcoe_csm_assembly
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/zhangxuedong/OpenMDAO-Framework/devenv/WISDEM/src/wisdem/lcoe/lcoe_csm_assembly.py", line 10, in <module>
from fusedwind.plant_cost.fused_finance import ExtendedFinancialAnalysis, configure_extended_financial_analysis
File "/usr/local/lib/python2.7/dist-packages/fusedwind-0.1.0-py2.7.egg/fusedwind/plant_cost/fused_finance.py", line 6, in <module>
from fusedwind.plant_flow.asym import BaseAEPModel
File "/usr/local/lib/python2.7/dist-packages/fusedwind-0.1.0-py2.7.egg/fusedwind/plant_flow/asym.py", line 7, in <module>
from openmdao.lib.drivers.api import CaseIteratorDriver
File "/usr/local/lib/python2.7/dist-packages/openmdao.lib-0.13.0-py2.7.egg/openmdao/lib/drivers/api.py", line 10, in <module>
from openmdao.lib.drivers.cobyladriver import COBYLAdriver
File "/usr/local/lib/python2.7/dist-packages/openmdao.lib-0.13.0-py2.7.egg/openmdao/lib/drivers/cobyladriver.py", line 15, in <module>
from cobyla.cobyla import cobyla, closeunit
ImportError: No module named cobyla.cobyla

**Comment by michaelXDzhang** [comment]
I fixed, passed all unit test on a Ubuntu 13 environment,but I got error again when I run example.py as below,need help
raceback (most recent call last):
File "./docs/examples/example.py", line 62, in <module>
lcoe.run()
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/component.py", line 549, in run
self._pre_execute()
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/component.py", line 469, in _pre_execute
self._setup()
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/assembly.py", line 1677, in _setup
self.setup_depgraph()
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/assembly.py", line 1261, in setup_depgraph
(src, dest), sys.exc_info())
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/assembly.py", line 1242, in setup_depgraph
self._depgraph.check_connect(src, dest)
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/depgraph.py", line 378, in check_connect
conns = self._var_connections(dpbase, 'in')
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/depgraph.py", line 722, in _var_connections
for u,v in self.var_edge_iter(path, reverse=True):
File "/usr/local/lib/python2.7/dist-packages/openmdao.main-0.13.0-py2.7.egg/openmdao/main/depgraph.py", line 734, in var_edge_iter
neighbors = self.predecessors_iter
AttributeError: : Can't connect 'tcc_a.turbine_cost' to 'turbine_cost': : 'DependencyGraph' object has no attribute 'predecessors_iter'

**Comment by michaelXDzhang** [comment]
a plug in SEAMLoads needed when i run leco_se_seam_assembly.py, I search source tree, no this module
from SEAMLoads.SEAMLoads import SEAMLoads
from SEAMTower.SEAMTower import SEAMTower
from SEAMAero.SEAM_AEP import SEAM_PowerCurve
from SEAMRotor.SEAMRotor import SEAMBladeStructure @dykesk

**Comment by michaelXDzhang** [comment]
I got thoses SEAM models and work on WISDEM

**Comment by dykesk** [comment]
Hello Michael - is this still an issue? Can i close this out? Your last comment seems that you have things working.

**Comment by michaelXDzhang** [comment]
Hi Kathrine,
Yes, you can close, I am running WISDEM very well  in my Ubuntu,  and I heard you did a FUSEDWIND convert codes , can I get some info? I could not find the codes on github.
I am doing system integration in our company and is it  possible to cooperation with you, as OEM we are lack of Models even the way to building model, eg, our generator model is directive drive,  RNA is quite diff, that’s be great to get to have some chance to cooperate with you .
Looking to hear,
Michael Zhang
[3]
张学东（Michael）
Senior System Engineer(Digital Wind Farm)
System Control & Simulation | R&D SBU
Beijing Goldwind Science & Creation windpower equipment Co., Ltd. （Company）
Add: No 8 Boxing Road 1, BDA, Yizhuang, Beijing, China, 100176
Tel：+86-(0)10- 67511888-6908
Mobile：+86-(0)15567532015



发件人: Katherine Dykes [mailto:notifications@github.com]
发送时间: 2018年5月2日 21:09
收件人: WISDEM/WISDEM
抄送: 张学东; Author
主题: Re: [WISDEM/WISDEM] cobyla.cobyla error (#49)


Hello Michael - is this still an issue? Can i close this out? Your last comment seems that you have things working.

**Comment by dykesk** [comment]
Hello Michael - since this is not a code issue; let's take the discussion offline - systems.engineering@nrel.gov
