### ISSUE TITLE
installing problem for CCBlade

### ISSUE THREAD

**Issue by lijunDEC** [WISDEM/WISDEM#51]
dear administrator,
I get a trouble when installing Wisdem, the traceback is attached following, looking forward you reply...
`Installed d:\programdata\wisdem\plugins\airfoilpreppy\src
subprocess returned  0
install url: package= CCBlade url=  http://github.com/WISDEM/CCBlade/tarball/mas
ter
Traceback (most recent call last):
  File "setup_all.py", line 105, in <module>
    install_url(f, url,force=options.force)
  File "setup_all.py", line 27, in install_url
    response = urllib2.urlopen(url)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\ProgramData\Python27Win32\Lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "D:\ProgramData\Python27Win32\Lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "D:\ProgramData\Python27Win32\Lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Python27Win32\Lib\httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

(openmdao-0.10.1) D:\ProgramData\WISDEM>`

**Comment by lijunDEC** [comment]
Dear administrator,
The above issue had been solved by reinstalling the wisdem, but when I  import wisdem.lcoe.lcoe_se_assembly or precomp.py ,the following issue troubles me, looking forward your reply.
`>>> import wisdem.lcoe.lcoe_se_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\programdata\wisdem\src\wisdem\lcoe\lcoe_se_assembly.py", line 19, in
<module>
    from wisdem.turbinese.turbine import configure_turbine
  File "d:\programdata\wisdem\src\wisdem\turbinese\turbine.py", line 15, in <mod
ule>
    from rotorse.rotor import RotorSE
  File "d:\programdata\wisdem\plugins\rotorse\src\rotorse\rotor.py", line 22, in
 <module>
    from precomp import Profile, Orthotropic2DMaterial, CompositeSection, _preco
mp
  File "d:\programdata\wisdem\plugins\rotorse\src\rotorse\precomp.py", line 18,
in <module>
    from _precomp import precomp as _precomp
ImportError: DLL load failed: 找不到指定的程序。`
