### ISSUE TITLE
Cannot install on linux arm64 (Mac M1)

### ISSUE THREAD

**Issue by cortadocodes** [WISDEM/WISDEM#531]
## Description
When trying to `pip install wisdem` in the `python:3.12.2` docker container on a Mac M1 host (arm64), I get an error and the installation fails.

### Steps to reproduce issue
1. Install docker
2. Run `docker run -it python:3.12.2 /bin/bash`
3. Run `pip install wisdem`

### Current behavior
```
pip install wisdem

Collecting wisdem
  Using cached wisdem-3.15.3.tar.gz (5.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      ['/tmp/pip-build-env-svt7sp3l/overlay/bin/meson', 'setup', 'meson_build', '--wipe', '--prefix=/tmp/pip-install-j051p6lk/wisdem_c826de1549bf4f6d9e03d551bd37025e/meson_build', '-Dpython.purelibdir=.', '-Dpython.platlibdir=.']
      
      ERROR: Neither source directory 'meson_build' nor build directory None contain a build file meson.build.
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svt7sp3l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svt7sp3l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-svt7sp3l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 102, in <module>
        File "<string>", line 62, in run_meson_build
      OSError: [Errno ['/tmp/pip-build-env-svt7sp3l/overlay/bin/meson', 'setup', 'meson_build', '--wipe', '--prefix=/tmp/pip-install-j051p6lk/wisdem_c826de1549bf4f6d9e03d551bd37025e/meson_build', '-Dpython.purelibdir=.', '-Dpython.platlibdir=.']] The meson setup command failed! Check the log at meson_build/setup.log for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Expected behavior
The installation succeeds.

### Code versions
- wisdem `3.15.3`
- Python `3.12.2`
- Container: `python:3.12.2`
- Host: M1 Mac (arm64)

**Comment by gbarter** [comment]
On Docker, even if you are running on a mac, I believe the pypi architecture that is needed is `linux_aarch64`.  I can see that isn't currently in the build matrix, so I'm testing out including that for better Docker support.

However, Mac `arm64` is indeed in the build matrix, and should be available to you via `pip install` or `conda install` if you choose to work outside of Docker.
