### ISSUE TITLE
Please reduce the number of cores, currently set to 1, to the number of finite differences 0

### ISSUE THREAD

**Issue by 15280560196** [WISDEM/WISDEM#549]
I'm getting an error when I  run WISDEM/examples/02_reference_turbines（Not just 02. I can't do all the cases）:

C:\Users\82698\.conda\envs\wisdem-env\python.exe C:\Users\82698\Desktop\test\WISDEM-master\WISDEM\examples\02_reference_turbines\nrel5mw_driver.py 
Traceback (most recent call last):
  File "C:\Users\82698\Desktop\test\WISDEM-master\WISDEM\examples\02_reference_turbines\nrel5mw_driver.py", line 12, in <module>
    wt_opt, analysis_options, opt_options = run_wisdem(fname_wt_input, fname_modeling_options, fname_analysis_options)
  File "D:\WISDEM\WISDEM-master\wisdem\glue_code\runWISDEM.py", line 46, in run_wisdem
    raise ValueError(
ValueError: ERROR: please reduce the number of cores, currently set to 1, to the number of finite differences 0, which is equal to the number of design variables DV for forward differencing and DV times 2 for central differencing, or the parallelization logic will not work

![d864c1caafff7af9b6daa2ec21d06e8](https://github.com/WISDEM/WISDEM/assets/106306315/ad4fa8e1-7550-41de-9063-d0963035a802)

**Comment by gbarter** [comment]
This is equally confusing as it is also an MPI error, but one that only arises when doing optimization, and there is no optimization active in that example.  Let's resolve the MPI issue in your other question first and then try this example again.

**Comment by ibrahim-hanif** [comment]
Hei, I encountered it as well, was a solution to this issue found?

**Comment by gbarter** [comment]
Is `mpi4py` installed in your environment?  If so, maybe try removing it.

**Comment by ibrahim-hanif** [comment]
yes it is, as listed by `conda list`. removing `mpi4py` would also remove
`The following packages will be REMOVED:

  mpi-1.0-msmpi
  mpi4py-4.0.0-py312ha74b32c_1
  msmpi-10.1.1-h3502643_7`
is it what we want, or would it be harmful?

**Comment by gbarter** [comment]
Yes, you can remove

**Comment by gbarter** [comment]
Hmm.  That also shouldn't happen.  Can you post the results of `conda list`?

**Comment by ibrahim-hanif** [comment]
thank you for your reply. yes, here it is:

```
conda list
# packages in environment at C:\Users\...\.conda\envs\wisdem-env:  
#
# Name                    Version                   Build  Channel      
alabaster                 1.0.0              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py312h53d5487_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h32b962e_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.17.0          py312h4389bb4_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h0d7def4_0    conda-forge
coverage                  7.6.1           py312h4389bb4_0    conda-forge
coveralls                 4.0.1              pyhd8ed1ab_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.11          py312h275cf98_0    conda-forge
dearpygui                 1.11.1                   pypi_0    pypi
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
double-conversion         3.3.0                h63175ca_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py312h4389bb4_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  9.0.0                h2bedf89_1    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he0c23c2_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.2              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
ipopt                     3.14.16              ha3daec3_4    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              23_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              23_win64_mkl    conda-forge
libclang13                18.1.8          default_ha5278ca_2    conda-forge
libdeflate                1.21                 h2466b09_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libglib                   2.80.3               h7025463_2    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              23_win64_mkl    conda-forge
libpgmath                 2021.08.06           h39d44d4_0    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpython                 2.2             py312h2e8e312_3    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libtiff                   4.6.0                hb151862_4    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 hcd874cb_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
make                      4.3                  h3d2af85_1    conda-forge
markupsafe                2.1.5           py312he70551f_0    conda-forge
marmot-agents             0.2.5                    pypi_0    pypi
matplotlib                3.9.2           py312h2e8e312_0    conda-forge
matplotlib-base           3.9.2           py312h90004f6_0    conda-forge
mdolab-baseclasses        1.8.0              pyhd8ed1ab_0    conda-forge
meson                     1.5.1              pyhd8ed1ab_1    conda-forge
metis                     5.1.0             h63175ca_1007    conda-forge
mkl                       2024.1.0           h66d3029_694    conda-forge
moorpy                    1.0.2              pyhd8ed1ab_0    conda-forge
mpi                       1.0                       msmpi    conda-forge
mpi4py                    4.0.0           py312ha74b32c_1    conda-forge
msmpi                     10.1.1               h3502643_7    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mumps-seq                 5.7.2                h7c2359a_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
ninja                     1.12.1               hc790b64_0    conda-forge
nlopt                     2.7.1           py312h1fad3b1_5    conda-forge
numpy                     1.26.4          py312h8753938_0    conda-forge
numpydoc                  1.8.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openmdao                  3.34.2             pyhd8ed1ab_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.1.5           py312he70551f_0    conda-forge
openssl                   3.3.1                h2466b09_3    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h72972c8_1    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_2    conda-forge
pillow                    10.4.0          py312h381445a_0    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydoe3                    1.0.3              pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyoptsparse               2.11.3          py312h2808998_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyside6                   6.7.2           py312h2ee7485_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytest                    8.3.2              pyhd8ed1ab_0    conda-forge
pytest-cov                5.0.0              pyhd8ed1ab_0    conda-forge
python                    3.12.5          h889d299_0_cpython    conda-forge
python-benedict           0.33.2             pyhd8ed1ab_0    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fsutil             0.14.1             pyhd8ed1ab_0    conda-forge
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h4389bb4_0    conda-forge
qhull                     2020.2               hc790b64_5    conda-forge
qt6-main                  6.7.2                hbb46ec1_4    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rpds-py                   0.20.0          py312h2615798_0    conda-forge
ruamel.yaml               0.18.6          py312he70551f_0    conda-forge
ruamel.yaml.clib          0.2.8           py312he70551f_0    conda-forge
scipy                     1.14.0          py312h1f4e10d_1    conda-forge
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
simpy                     4.1.1              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    8.0.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.1.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.10             pyhd8ed1ab_0    conda-forge
sqlitedict                2.1.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2          py312h1a27103_0    conda-forge
swig                      4.2.1                h51fbe9b_1    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.12.0            hc790b64_3    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h4389bb4_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wisdem                    3.16.4          py312h54ab778_100    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.20.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zstandard                 0.23.0          py312h7606c53_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

**Comment by gbarter** [comment]
`mpi4py` is there- did you reinstall it?

**Comment by ibrahim-hanif** [comment]
yes i reinstalled it to recheck if previous examples work (01_nrel_csm), and it did… but got the 
‘‘‘
ValueError: ERROR: please reduce the number of cores, currently set to 1, to the number of finite differences 0, which is equal to the number of design variables DV for forward differencing and DV times 2 for central differencing, or the parallelization logic will not work
‘‘‘
with examples 02_ and 03_ again. :/

**Comment by gbarter** [comment]
PR #560 should hopefully fix the immediate issue, but overall this is still puzzling to us since it isn't how the code logic is written and other Windows machines (including the ones on Github Actions) do not have this issue.

Are you comfortable switching to a branch?

**Comment by ibrahim-hanif** [comment]
Hi, thank you for checking the issue at your local systems and for the immediate bugfix. 
Yes, switching to a branch should be fine.

**Comment by gbarter** [comment]
Try `git checkout develop` and see if the error persists

**Comment by ibrahim-hanif** [comment]
the bugfix works wonderfully, thanks for the assistance 😊 I could run the other examples as well.
(currently working with the geared drivetrain example (5MW), which refuses to converge even after 15 iterations ;p)

**Comment by FelixMehlan** [comment]
I have the same issue with the mpi4py module and the number of cores error as describe above. I installed the mpi4py module and switched to the develop branch, however, the bug fix does not seem to work for me. I still receive the same error message. Any ideas?

```
(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml
Traceback (most recent call last):
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 10, in <module>
    sys.exit(wisdem_cmd())
             ^^^^^^^^^^^^
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\main.py", line 75, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 49, in run_wisdem
    raise ValueError(
ValueError: ERROR: please reduce the number of cores, currently set to 1, to the number of finite differences 0, which is equal to the number of design variables DV for forward differencing and DV times 2 for central differencing, or the parallelization logic will not work

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>
```

**Comment by gbarter** [comment]
Be sure to do a `git pull` after switching branches.

**Comment by FelixMehlan** [comment]
I did a git pull and I also checked manually that my local file \wisdem\glue_code\runWISDEM.py is updated with the changes in PR #560.

```
(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>git pull
Already up to date.

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml
Traceback (most recent call last):
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 10, in <module>
    sys.exit(wisdem_cmd())
             ^^^^^^^^^^^^
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\main.py", line 75, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felixcme\AppData\Local\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 49, in run_wisdem
    raise ValueError(
ValueError: ERROR: please reduce the number of cores, currently set to 1, to the number of finite differences 0, which is equal to the number of design variables DV for forward differencing and DV times 2 for central differencing, or the parallelization logic will not work

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>
```

**Comment by gbarter** [comment]
Ugh.  I will do my best to recreate the error to understand better what is going on.  Can you confirm that if you do a `git status` that you don't have any local edits to the files?

**Comment by FelixMehlan** [comment]
This is response to `git status`

```
(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../01_nrel_csm/parametric_scaling.csv
        coloring_files/
        outputs/
        temp1.yaml
        temp2.yaml
        test.csv
        ../05_tower_monopile/analysis_options_COBYLA.yaml
        ../05_tower_monopile/analysis_options_GA.yaml
        ../05_tower_monopile/analysis_options_LD_SLSQP.yaml
        ../05_tower_monopile/analysis_options_Nelder-Mead.yaml
        ../../test/test.npz
        ../../test/test.pkl
        ../../test/test.xlsx

nothing added to commit but untracked files present (use "git add" to track)

(wisdem-env) C:\Users\felixcme\WISDEM\examples\02_reference_turbines>
```

**Comment by gbarter** [comment]
Thank you

**Comment by gbarter** [comment]
I have not been able to recreate this error.  My best advice is to start with a new conda environment following the build instructions on the ReadMe, where `mpi` should not be installed at all on Windows.  I know that takes a bit of time to setup, so I appreciate your patience.
