### ISSUE TITLE
After successfully installing m2w64-toolchain libpython, Conda runs code that prompts "No module named 'mpi4py'"

### ISSUE THREAD

**Issue by 15280560196** [WISDEM/WISDEM#550]
## Description
Conda has a problem installing m2w64-toolchain libpython. Running the code prompts "No module named 'mpi4py'"

C:\Users\82698\.conda\envs\WISDEM_TEST\python.exe C:\Users\82698\Desktop\test\WISDEM-master\WISDEM\examples\02_reference_turbines\nrel5mw_driver.py 
Traceback (most recent call last):
  File "C:\Users\82698\Desktop\test\WISDEM-master\WISDEM\examples\02_reference_turbines\nrel5mw_driver.py", line 4, in <module>
    from wisdem import run_wisdem
  File "C:\Users\82698\.conda\envs\WISDEM_TEST\Lib\site-packages\wisdem\__init__.py", line 1, in <module>
    from wisdem.glue_code.runWISDEM import run_wisdem
  File "C:\Users\82698\.conda\envs\WISDEM_TEST\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 10, in <module>
    from wisdem.commonse.mpi_tools import MPI
  File "C:\Users\82698\.conda\envs\WISDEM_TEST\Lib\site-packages\wisdem\commonse\mpi_tools.py", line 29, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'

![f79abfb545c4c01a3a214d0b111cdb0](https://github.com/WISDEM/WISDEM/assets/106306315/4ed1623e-44da-44f4-b2c3-f286972876fd)
![cd0b402fbd23ae7251834e1dc90d705](https://github.com/WISDEM/WISDEM/assets/106306315/32693dcb-7b27-4388-b257-9ae312161cd9)

**Comment by gbarter** [comment]
Hmm, this is confusing to me.  I cannot recreate the issue on my Windows machine and the error you are getting is really a [check](https://github.com/WISDEM/WISDEM/blob/master/wisdem/commonse/mpi_tools.py#L4) to see if `mpi4py` is installed at all, and then to mark a flag false if not.  A few of requests/options for you:

1. Could you please type `conda list` and then report back what is there
2. Move to the `develop` branch by doing `git checkout develop` anywhere within the WISDEM directory.  Then try rerunning the example.
3. If step no. 2 doesn't fix things, try to install mpi4py with `conda install mpi4py`.  Then try rerunning the example.

**Comment by 15280560196** [comment]
Hi I reinstalled WISDEM according to the latest updated tutorial, but the problem is still the same. Now I will show you part of the process and the installation package.











826986507
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WISDEM/WISDEM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月3日(星期三) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WISDEM/WISDEM] After successfully installing m2w64-toolchain libpython, Conda runs code that prompts "No module named 'mpi4py'" (Issue #550)





 
Hmm, this is confusing to me.  I cannot recreate the issue on my Windows machine and the error you are getting is really a check to see if mpi4py is installed at all, and then to mark a flag false if not.  A few of requests/options for you:
  
Could you please type conda list and then report back what is there
 
Move to the develop branch by doing git checkout develop anywhere within the WISDEM directory.  Then try rerunning the example.
 
If step no. 2 doesn't fix things, try to install mpi4py with conda install mpi4py.  Then try rerunning the example.

**Comment by 15280560196** [comment]
I get a new error when I use this method. “If step no. 2 doesn't fix things, try to install mpi4py with conda install mpi4py. Then try rerunning the example.”


826986507
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WISDEM/WISDEM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月3日(星期三) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WISDEM/WISDEM] After successfully installing m2w64-toolchain libpython, Conda runs code that prompts "No module named 'mpi4py'" (Issue #550)





 
Hmm, this is confusing to me.  I cannot recreate the issue on my Windows machine and the error you are getting is really a check to see if mpi4py is installed at all, and then to mark a flag false if not.  A few of requests/options for you:
  
Could you please type conda list and then report back what is there
 
Move to the develop branch by doing git checkout develop anywhere within the WISDEM directory.  Then try rerunning the example.
 
If step no. 2 doesn't fix things, try to install mpi4py with conda install mpi4py.  Then try rerunning the example.

**Comment by gbarter** [comment]
Your screen shots or copy-paste did not come through at all.  I cannot see what the issue is.  Can you try again to paste a screenshot?

**Comment by TheMercer** [comment]
I got this same error install my fresh installation earlier. So I conda install mpi4py, and it worked

**Comment by gbarter** [comment]
Thank you for this tip.  The `mpi4py` package can be a bit finicky on Windows.  We've tried not to rely on it, but I am glad that it worked in this case.
