### ISSUE TITLE
Changing glue code not affecting behavior when running through GUI

### ISSUE THREAD

**Issue by nkbw33** [WISDEM/WISDEM#567]
My lab is trying to fork WISDEM for a specific application and so I have been trying to modify the code. However, whenever I make changes - so far I've mostly been editing glue_code.py - it does not seem to have any affect on the output when ran through the GUI. Does anyone have any idea why this is?

**Comment by gbarter** [comment]
I suspect that WISDEM is not installed in "editable" mode and is therefore not seeing your changes.  If you open a python prompt and do:
```
>> import wisdem
>> wisdem.__file__
```
What does it say?

**Comment by nkbw33** [comment]
`import wisdem
C:\Users\Noam\WISDEM\wisdem\rotorse\geometry_tools\geom_tools.py:76: SyntaxWarning: invalid escape sequence '\p'
  """
C:\Users\Noam\WISDEM\wisdem\rotorse\geometry_tools\geom_tools.py:90: SyntaxWarning: invalid escape sequence '\p'
  """
C:\Users\Noam\WISDEM\wisdem\rotorse\geometry_tools\geom_tools.py:100: SyntaxWarning: invalid escape sequence '\p'
  """
C:\Users\Noam\WISDEM\wisdem\rotorse\geometry_tools\geom_tools.py:166: SyntaxWarning: invalid escape sequence '\l'
  """
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Noam\WISDEM\wisdem\__init__.py", line 1, in <module>
    from wisdem.glue_code.runWISDEM import run_wisdem
  File "C:\Users\Noam\WISDEM\wisdem\glue_code\runWISDEM.py", line 12, in <module>
    from wisdem.glue_code.glue_code import WindPark
  File "C:\Users\Noam\WISDEM\wisdem\glue_code\glue_code.py", line 5, in <module>
    from wisdem.rotorse.rotor import RotorSEProp, RotorSEPerf, RotorSE
  File "C:\Users\Noam\WISDEM\wisdem\rotorse\rotor.py", line 4, in <module>
    from wisdem.rotorse.rotor_power import RotorPower, NoStallConstraint
  File "C:\Users\Noam\WISDEM\wisdem\rotorse\rotor_power.py", line 16, in <module>
    from wisdem.ccblade.ccblade import CCBlade, CCAirfoil
  File "C:\Users\Noam\WISDEM\wisdem\ccblade\ccblade.py", line 31, in <module>
    import wisdem.ccblade._bem as _bem
ModuleNotFoundError: No module named 'wisdem.ccblade._bem'
wisdem.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'wisdem' is not defined`

This is what I get. I'm not sure why it says that wisdem is not defined, I can run the GUI.

**Comment by gbarter** [comment]
It actually looks like WISDEM failed to install correctly.  My guess is that while you may be able to pop up the GUI, there are errors in the back end when you click "Run", which is why you aren't seeing any difference.  Try running one of the reference turbine examples in the "02" directory from the command line.  That will probably error out too.

On Windows, we recommend using Miniconda and you'll need to install the gfortran compiler per the instructions.

**Comment by nkbw33** [comment]
`=========
wt.wt_rna
=========
←[00m←[00m←[00m←[00mNL: NLBGS 1 ; 4.06371192e+11 1
←[00m←[00m←[00m←[00mNL: NLBGS 2 ; 4760438.93 1.17145088e-05
←[00m←[00m←[00m←[00mNL: NLBGS 3 ; 0 0
NL: NLBGS Converged
←[00mFutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\FoundationCost.py:668
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:653
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\CollectionCost.py:847
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\Users\Noam\anaconda3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\ErectionCost.py:695
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.########################################
Objectives
Turbine AEP: 23.9127972556 GWh
Blade Mass:  16419.8666989212 kg
LCOE:        51.0804383502 USD/MWh
Tip Defl.:   4.7295143980 m
########################################
Completed in, 24.548314809799194 seconds`

This is what I get when I run an example.

**Comment by gbarter** [comment]
Okay, good, it looks like WISDEM is installed and working.  The prior error was just an unlucky factor of calling the command from inside the WISDEM directory.  However, I can also see that WISDEM is indeed installed without "editable" mode.  I would suggest doing this from the "C:\Users\Noam\WISDEM" directory:
```
conda remove wisdem
pip uninstall wisdem
pip install --no-deps -e . -vv
```

My concern is that the uninstall command also removes some of the needed dependencies, but we'll tackle one challenge at a time.

**Comment by nkbw33** [comment]
I tried a few different directories and environments and keep getting this:

`PackagesNotFoundError: The following packages are missing from the target environment:
  - wisdem`

**Comment by gbarter** [comment]
Okay, sounds good.  That is an okay error message.  Did you do `pip uninstall wisdem` too?

**Comment by nkbw33** [comment]
Not yet but I'll do that right now. I just wanted to make sure I didn't make a silly mistake again.

**Comment by nkbw33** [comment]
Alright, I installed it. Thank you for all your help. I will let you know if editing works now.
